# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AuthServerInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, token_url: str=None):  # noqa: E501
        """AuthServerInfo - a model defined in Swagger

        :param token_url: The token_url of this AuthServerInfo.  # noqa: E501
        :type token_url: str
        """
        self.swagger_types = {
            'token_url': str
        }

        self.attribute_map = {
            'token_url': 'tokenURL'
        }
        self._token_url = token_url

    @classmethod
    def from_dict(cls, dikt) -> 'AuthServerInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The authServerInfo of this AuthServerInfo.  # noqa: E501
        :rtype: AuthServerInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token_url(self) -> str:
        """Gets the token_url of this AuthServerInfo.

        URL of the token endpoint.  # noqa: E501

        :return: The token_url of this AuthServerInfo.
        :rtype: str
        """
        return self._token_url

    @token_url.setter
    def token_url(self, token_url: str):
        """Sets the token_url of this AuthServerInfo.

        URL of the token endpoint.  # noqa: E501

        :param token_url: The token_url of this AuthServerInfo.
        :type token_url: str
        """
        if token_url is None:
            raise ValueError("Invalid value for `token_url`, must not be `None`")  # noqa: E501

        self._token_url = token_url
