# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.resource_name import ResourceName  # noqa: F401,E501
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class BaseResourceRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, resource_name: ResourceName=None, ven_id: ObjectID=None, attributes: List[ValuesMap]=None):  # noqa: E501
        """BaseResourceRequest - a model defined in Swagger

        :param resource_name: The resource_name of this BaseResourceRequest.  # noqa: E501
        :type resource_name: ResourceName
        :param ven_id: The ven_id of this BaseResourceRequest.  # noqa: E501
        :type ven_id: ObjectID
        :param attributes: The attributes of this BaseResourceRequest.  # noqa: E501
        :type attributes: List[ValuesMap]
        """
        self.swagger_types = {
            'resource_name': ResourceName,
            'ven_id': ObjectID,
            'attributes': List[ValuesMap]
        }

        self.attribute_map = {
            'resource_name': 'resourceName',
            'ven_id': 'venID',
            'attributes': 'attributes'
        }
        self._resource_name = resource_name
        self._ven_id = ven_id
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'BaseResourceRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseResourceRequest of this BaseResourceRequest.  # noqa: E501
        :rtype: BaseResourceRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resource_name(self) -> ResourceName:
        """Gets the resource_name of this BaseResourceRequest.


        :return: The resource_name of this BaseResourceRequest.
        :rtype: ResourceName
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name: ResourceName):
        """Sets the resource_name of this BaseResourceRequest.


        :param resource_name: The resource_name of this BaseResourceRequest.
        :type resource_name: ResourceName
        """
        if resource_name is None:
            raise ValueError("Invalid value for `resource_name`, must not be `None`")  # noqa: E501

        self._resource_name = resource_name

    @property
    def ven_id(self) -> ObjectID:
        """Gets the ven_id of this BaseResourceRequest.


        :return: The ven_id of this BaseResourceRequest.
        :rtype: ObjectID
        """
        return self._ven_id

    @ven_id.setter
    def ven_id(self, ven_id: ObjectID):
        """Sets the ven_id of this BaseResourceRequest.


        :param ven_id: The ven_id of this BaseResourceRequest.
        :type ven_id: ObjectID
        """

        self._ven_id = ven_id

    @property
    def attributes(self) -> List[ValuesMap]:
        """Gets the attributes of this BaseResourceRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :return: The attributes of this BaseResourceRequest.
        :rtype: List[ValuesMap]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[ValuesMap]):
        """Sets the attributes of this BaseResourceRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :param attributes: The attributes of this BaseResourceRequest.
        :type attributes: List[ValuesMap]
        """

        self._attributes = attributes
