# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.resource import Resource  # noqa: F401,E501
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
from swagger_server.models.ven_name import VenName  # noqa: F401,E501
from swagger_server import util


class BaseVenRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ven_name: VenName=None, attributes: List[ValuesMap]=None, resources: List[Resource]=None):  # noqa: E501
        """BaseVenRequest - a model defined in Swagger

        :param ven_name: The ven_name of this BaseVenRequest.  # noqa: E501
        :type ven_name: VenName
        :param attributes: The attributes of this BaseVenRequest.  # noqa: E501
        :type attributes: List[ValuesMap]
        :param resources: The resources of this BaseVenRequest.  # noqa: E501
        :type resources: List[Resource]
        """
        self.swagger_types = {
            'ven_name': VenName,
            'attributes': List[ValuesMap],
            'resources': List[Resource]
        }

        self.attribute_map = {
            'ven_name': 'venName',
            'attributes': 'attributes',
            'resources': 'resources'
        }
        self._ven_name = ven_name
        self._attributes = attributes
        self._resources = resources

    @classmethod
    def from_dict(cls, dikt) -> 'BaseVenRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BaseVenRequest of this BaseVenRequest.  # noqa: E501
        :rtype: BaseVenRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ven_name(self) -> VenName:
        """Gets the ven_name of this BaseVenRequest.


        :return: The ven_name of this BaseVenRequest.
        :rtype: VenName
        """
        return self._ven_name

    @ven_name.setter
    def ven_name(self, ven_name: VenName):
        """Sets the ven_name of this BaseVenRequest.


        :param ven_name: The ven_name of this BaseVenRequest.
        :type ven_name: VenName
        """
        if ven_name is None:
            raise ValueError("Invalid value for `ven_name`, must not be `None`")  # noqa: E501

        self._ven_name = ven_name

    @property
    def attributes(self) -> List[ValuesMap]:
        """Gets the attributes of this BaseVenRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :return: The attributes of this BaseVenRequest.
        :rtype: List[ValuesMap]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[ValuesMap]):
        """Sets the attributes of this BaseVenRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :param attributes: The attributes of this BaseVenRequest.
        :type attributes: List[ValuesMap]
        """

        self._attributes = attributes

    @property
    def resources(self) -> List[Resource]:
        """Gets the resources of this BaseVenRequest.

        A list of resource objects representing end-devices or systems.  # noqa: E501

        :return: The resources of this BaseVenRequest.
        :rtype: List[Resource]
        """
        return self._resources

    @resources.setter
    def resources(self, resources: List[Resource]):
        """Sets the resources of this BaseVenRequest.

        A list of resource objects representing end-devices or systems.  # noqa: E501

        :param resources: The resources of this BaseVenRequest.
        :type resources: List[Resource]
        """

        self._resources = resources
