# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.client_id import ClientID  # noqa: F401,E501
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.resource_name import ResourceName  # noqa: F401,E501
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class BlResourceRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, object_type: str=None, client_id: ClientID=None, targets: List[ValuesMap]=None, resource_name: ResourceName=None, ven_id: ObjectID=None, attributes: List[ValuesMap]=None):  # noqa: E501
        """BlResourceRequest - a model defined in Swagger

        :param object_type: The object_type of this BlResourceRequest.  # noqa: E501
        :type object_type: str
        :param client_id: The client_id of this BlResourceRequest.  # noqa: E501
        :type client_id: ClientID
        :param targets: The targets of this BlResourceRequest.  # noqa: E501
        :type targets: List[ValuesMap]
        :param resource_name: The resource_name of this BlResourceRequest.  # noqa: E501
        :type resource_name: ResourceName
        :param ven_id: The ven_id of this BlResourceRequest.  # noqa: E501
        :type ven_id: ObjectID
        :param attributes: The attributes of this BlResourceRequest.  # noqa: E501
        :type attributes: List[ValuesMap]
        """
        self.swagger_types = {
            'object_type': str,
            'client_id': ClientID,
            'targets': List[ValuesMap],
            'resource_name': ResourceName,
            'ven_id': ObjectID,
            'attributes': List[ValuesMap]
        }

        self.attribute_map = {
            'object_type': 'objectType',
            'client_id': 'clientID',
            'targets': 'targets',
            'resource_name': 'resourceName',
            'ven_id': 'venID',
            'attributes': 'attributes'
        }
        self._object_type = object_type
        self._client_id = client_id
        self._targets = targets
        self._resource_name = resource_name
        self._ven_id = ven_id
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'BlResourceRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BlResourceRequest of this BlResourceRequest.  # noqa: E501
        :rtype: BlResourceRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def object_type(self) -> str:
        """Gets the object_type of this BlResourceRequest.

        Used as discriminator.  # noqa: E501

        :return: The object_type of this BlResourceRequest.
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type: str):
        """Sets the object_type of this BlResourceRequest.

        Used as discriminator.  # noqa: E501

        :param object_type: The object_type of this BlResourceRequest.
        :type object_type: str
        """
        allowed_values = ["BL_RESOURCE_REQUEST"]  # noqa: E501
        if object_type not in allowed_values:
            raise ValueError(
                "Invalid value for `object_type` ({0}), must be one of {1}"
                .format(object_type, allowed_values)
            )

        self._object_type = object_type

    @property
    def client_id(self) -> ClientID:
        """Gets the client_id of this BlResourceRequest.


        :return: The client_id of this BlResourceRequest.
        :rtype: ClientID
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: ClientID):
        """Sets the client_id of this BlResourceRequest.


        :param client_id: The client_id of this BlResourceRequest.
        :type client_id: ClientID
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def targets(self) -> List[ValuesMap]:
        """Gets the targets of this BlResourceRequest.

        A list of valuesMap objects describing target criteria.  # noqa: E501

        :return: The targets of this BlResourceRequest.
        :rtype: List[ValuesMap]
        """
        return self._targets

    @targets.setter
    def targets(self, targets: List[ValuesMap]):
        """Sets the targets of this BlResourceRequest.

        A list of valuesMap objects describing target criteria.  # noqa: E501

        :param targets: The targets of this BlResourceRequest.
        :type targets: List[ValuesMap]
        """

        self._targets = targets

    @property
    def resource_name(self) -> ResourceName:
        """Gets the resource_name of this BlResourceRequest.


        :return: The resource_name of this BlResourceRequest.
        :rtype: ResourceName
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name: ResourceName):
        """Sets the resource_name of this BlResourceRequest.


        :param resource_name: The resource_name of this BlResourceRequest.
        :type resource_name: ResourceName
        """
        if resource_name is None:
            raise ValueError("Invalid value for `resource_name`, must not be `None`")  # noqa: E501

        self._resource_name = resource_name

    @property
    def ven_id(self) -> ObjectID:
        """Gets the ven_id of this BlResourceRequest.


        :return: The ven_id of this BlResourceRequest.
        :rtype: ObjectID
        """
        return self._ven_id

    @ven_id.setter
    def ven_id(self, ven_id: ObjectID):
        """Sets the ven_id of this BlResourceRequest.


        :param ven_id: The ven_id of this BlResourceRequest.
        :type ven_id: ObjectID
        """
        if ven_id is None:
            raise ValueError("Invalid value for `ven_id`, must not be `None`")  # noqa: E501

        self._ven_id = ven_id

    @property
    def attributes(self) -> List[ValuesMap]:
        """Gets the attributes of this BlResourceRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :return: The attributes of this BlResourceRequest.
        :rtype: List[ValuesMap]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[ValuesMap]):
        """Sets the attributes of this BlResourceRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :param attributes: The attributes of this BlResourceRequest.
        :type attributes: List[ValuesMap]
        """

        self._attributes = attributes
