# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.client_id import ClientID  # noqa: F401,E501
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
from swagger_server.models.ven_name import VenName  # noqa: F401,E501
from swagger_server import util


class BlVenRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, object_type: str=None, client_id: ClientID=None, targets: List[ValuesMap]=None, ven_name: VenName=None, attributes: List[ValuesMap]=None):  # noqa: E501
        """BlVenRequest - a model defined in Swagger

        :param object_type: The object_type of this BlVenRequest.  # noqa: E501
        :type object_type: str
        :param client_id: The client_id of this BlVenRequest.  # noqa: E501
        :type client_id: ClientID
        :param targets: The targets of this BlVenRequest.  # noqa: E501
        :type targets: List[ValuesMap]
        :param ven_name: The ven_name of this BlVenRequest.  # noqa: E501
        :type ven_name: VenName
        :param attributes: The attributes of this BlVenRequest.  # noqa: E501
        :type attributes: List[ValuesMap]
        """
        self.swagger_types = {
            'object_type': str,
            'client_id': ClientID,
            'targets': List[ValuesMap],
            'ven_name': VenName,
            'attributes': List[ValuesMap]
        }

        self.attribute_map = {
            'object_type': 'objectType',
            'client_id': 'clientID',
            'targets': 'targets',
            'ven_name': 'venName',
            'attributes': 'attributes'
        }
        self._object_type = object_type
        self._client_id = client_id
        self._targets = targets
        self._ven_name = ven_name
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'BlVenRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BlVenRequest of this BlVenRequest.  # noqa: E501
        :rtype: BlVenRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def object_type(self) -> str:
        """Gets the object_type of this BlVenRequest.

        Used as discriminator.  # noqa: E501

        :return: The object_type of this BlVenRequest.
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type: str):
        """Sets the object_type of this BlVenRequest.

        Used as discriminator.  # noqa: E501

        :param object_type: The object_type of this BlVenRequest.
        :type object_type: str
        """
        allowed_values = ["BL_VEN_REQUEST"]  # noqa: E501
        if object_type not in allowed_values:
            raise ValueError(
                "Invalid value for `object_type` ({0}), must be one of {1}"
                .format(object_type, allowed_values)
            )

        self._object_type = object_type

    @property
    def client_id(self) -> ClientID:
        """Gets the client_id of this BlVenRequest.


        :return: The client_id of this BlVenRequest.
        :rtype: ClientID
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: ClientID):
        """Sets the client_id of this BlVenRequest.


        :param client_id: The client_id of this BlVenRequest.
        :type client_id: ClientID
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def targets(self) -> List[ValuesMap]:
        """Gets the targets of this BlVenRequest.

        A list of valuesMap objects describing target criteria.  # noqa: E501

        :return: The targets of this BlVenRequest.
        :rtype: List[ValuesMap]
        """
        return self._targets

    @targets.setter
    def targets(self, targets: List[ValuesMap]):
        """Sets the targets of this BlVenRequest.

        A list of valuesMap objects describing target criteria.  # noqa: E501

        :param targets: The targets of this BlVenRequest.
        :type targets: List[ValuesMap]
        """

        self._targets = targets

    @property
    def ven_name(self) -> VenName:
        """Gets the ven_name of this BlVenRequest.


        :return: The ven_name of this BlVenRequest.
        :rtype: VenName
        """
        return self._ven_name

    @ven_name.setter
    def ven_name(self, ven_name: VenName):
        """Sets the ven_name of this BlVenRequest.


        :param ven_name: The ven_name of this BlVenRequest.
        :type ven_name: VenName
        """
        if ven_name is None:
            raise ValueError("Invalid value for `ven_name`, must not be `None`")  # noqa: E501

        self._ven_name = ven_name

    @property
    def attributes(self) -> List[ValuesMap]:
        """Gets the attributes of this BlVenRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :return: The attributes of this BlVenRequest.
        :rtype: List[ValuesMap]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[ValuesMap]):
        """Sets the attributes of this BlVenRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :param attributes: The attributes of this BlVenRequest.
        :type attributes: List[ValuesMap]
        """

        self._attributes = attributes
