# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.event_payload_descriptor import EventPayloadDescriptor  # noqa: F401,E501
from swagger_server.models.interval import Interval  # noqa: F401,E501
from swagger_server.models.interval_period import IntervalPeriod  # noqa: F401,E501
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.report_descriptor import ReportDescriptor  # noqa: F401,E501
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class EventRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, program_id=None, event_name=None, duration=None, priority=None, targets=None, report_descriptors=None, payload_descriptors=None, interval_period=None, intervals=None):  # noqa: E501
        """EventRequest - a model defined in OpenAPI

        :param program_id: The program_id of this EventRequest.  # noqa: E501
        :type program_id: ObjectID
        :param event_name: The event_name of this EventRequest.  # noqa: E501
        :type event_name: str
        :param duration: The duration of this EventRequest.  # noqa: E501
        :type duration: str
        :param priority: The priority of this EventRequest.  # noqa: E501
        :type priority: int
        :param targets: The targets of this EventRequest.  # noqa: E501
        :type targets: List[ValuesMap]
        :param report_descriptors: The report_descriptors of this EventRequest.  # noqa: E501
        :type report_descriptors: List[ReportDescriptor]
        :param payload_descriptors: The payload_descriptors of this EventRequest.  # noqa: E501
        :type payload_descriptors: List[EventPayloadDescriptor]
        :param interval_period: The interval_period of this EventRequest.  # noqa: E501
        :type interval_period: IntervalPeriod
        :param intervals: The intervals of this EventRequest.  # noqa: E501
        :type intervals: List[Interval]
        """
        self.swagger_types = {
            'program_id': ObjectID,
            'event_name': str,
            'duration': str,
            'priority': int,
            'targets': List[ValuesMap],
            'report_descriptors': List[ReportDescriptor],
            'payload_descriptors': List[EventPayloadDescriptor],
            'interval_period': IntervalPeriod,
            'intervals': List[Interval]
        }

        self.attribute_map = {
            'program_id': 'programID',
            'event_name': 'eventName',
            'duration': 'duration',
            'priority': 'priority',
            'targets': 'targets',
            'report_descriptors': 'reportDescriptors',
            'payload_descriptors': 'payloadDescriptors',
            'interval_period': 'intervalPeriod',
            'intervals': 'intervals'
        }
        self._program_id = program_id
        self._event_name = event_name
        self._duration = duration
        self._priority = priority
        self._targets = targets
        self._report_descriptors = report_descriptors
        self._payload_descriptors = payload_descriptors
        self._interval_period = interval_period
        self._intervals = intervals

    @classmethod
    def from_dict(cls, dikt) -> 'EventRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The eventRequest of this EventRequest.  # noqa: E501
        :rtype: EventRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def program_id(self) -> ObjectID:
        """Gets the program_id of this EventRequest.

        URL safe VTN assigned object ID.  # noqa: E501

        :return: The program_id of this EventRequest.
        :rtype: ObjectID
        """
        return self._program_id

    @program_id.setter
    def program_id(self, program_id: ObjectID):
        """Sets the program_id of this EventRequest.

        URL safe VTN assigned object ID.  # noqa: E501

        :param program_id: The program_id of this EventRequest.
        :type program_id: ObjectID
        """
        if program_id is None:
            raise ValueError("Invalid value for `program_id`, must not be `None`")  # noqa: E501
        if program_id is not None and len(program_id) > 128:
            raise ValueError("Invalid value for `program_id`, length must be less than or equal to `128`")  # noqa: E501
        if program_id is not None and len(program_id) < 1:
            raise ValueError("Invalid value for `program_id`, length must be greater than or equal to `1`")  # noqa: E501
        if program_id is not None and not re.search(r'^[a-zA-Z0-9_-]*$', program_id):  # noqa: E501
            raise ValueError(r"Invalid value for `program_id`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]*$/`")  # noqa: E501

        self._program_id = program_id

    @property
    def event_name(self) -> str:
        """Gets the event_name of this EventRequest.

        User defined string for use in debugging or User Interface.  # noqa: E501

        :return: The event_name of this EventRequest.
        :rtype: str
        """
        return self._event_name

    @event_name.setter
    def event_name(self, event_name: str):
        """Sets the event_name of this EventRequest.

        User defined string for use in debugging or User Interface.  # noqa: E501

        :param event_name: The event_name of this EventRequest.
        :type event_name: str
        """

        self._event_name = event_name

    @property
    def duration(self) -> str:
        """Gets the duration of this EventRequest.

        duration in ISO 8601 format  # noqa: E501

        :return: The duration of this EventRequest.
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration: str):
        """Sets the duration of this EventRequest.

        duration in ISO 8601 format  # noqa: E501

        :param duration: The duration of this EventRequest.
        :type duration: str
        """
        if duration is not None and not re.search(r'^(-?)P(?=\d|T\d)(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)([DW]))?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$', duration):  # noqa: E501
            raise ValueError(r"Invalid value for `duration`, must be a follow pattern or equal to `/^(-?)P(?=\d|T\d)(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)([DW]))?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$/`")  # noqa: E501

        self._duration = duration

    @property
    def priority(self) -> int:
        """Gets the priority of this EventRequest.

        Relative priority of event. A lower number is a higher priority.  # noqa: E501

        :return: The priority of this EventRequest.
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority: int):
        """Sets the priority of this EventRequest.

        Relative priority of event. A lower number is a higher priority.  # noqa: E501

        :param priority: The priority of this EventRequest.
        :type priority: int
        """
        if priority is not None and priority < 0:  # noqa: E501
            raise ValueError("Invalid value for `priority`, must be a value greater than or equal to `0`")  # noqa: E501

        self._priority = priority

    @property
    def targets(self) -> List[ValuesMap]:
        """Gets the targets of this EventRequest.

        A list of valuesMap objects.  # noqa: E501

        :return: The targets of this EventRequest.
        :rtype: List[ValuesMap]
        """
        return self._targets

    @targets.setter
    def targets(self, targets: List[ValuesMap]):
        """Sets the targets of this EventRequest.

        A list of valuesMap objects.  # noqa: E501

        :param targets: The targets of this EventRequest.
        :type targets: List[ValuesMap]
        """

        self._targets = targets

    @property
    def report_descriptors(self) -> List[ReportDescriptor]:
        """Gets the report_descriptors of this EventRequest.

        A list of reportDescriptor objects. Used to request reports from VEN.  # noqa: E501

        :return: The report_descriptors of this EventRequest.
        :rtype: List[ReportDescriptor]
        """
        return self._report_descriptors

    @report_descriptors.setter
    def report_descriptors(self, report_descriptors: List[ReportDescriptor]):
        """Sets the report_descriptors of this EventRequest.

        A list of reportDescriptor objects. Used to request reports from VEN.  # noqa: E501

        :param report_descriptors: The report_descriptors of this EventRequest.
        :type report_descriptors: List[ReportDescriptor]
        """

        self._report_descriptors = report_descriptors

    @property
    def payload_descriptors(self) -> List[EventPayloadDescriptor]:
        """Gets the payload_descriptors of this EventRequest.

        A list of payloadDescriptor objects.  # noqa: E501

        :return: The payload_descriptors of this EventRequest.
        :rtype: List[EventPayloadDescriptor]
        """
        return self._payload_descriptors

    @payload_descriptors.setter
    def payload_descriptors(self, payload_descriptors: List[EventPayloadDescriptor]):
        """Sets the payload_descriptors of this EventRequest.

        A list of payloadDescriptor objects.  # noqa: E501

        :param payload_descriptors: The payload_descriptors of this EventRequest.
        :type payload_descriptors: List[EventPayloadDescriptor]
        """

        self._payload_descriptors = payload_descriptors

    @property
    def interval_period(self) -> IntervalPeriod:
        """Gets the interval_period of this EventRequest.


        :return: The interval_period of this EventRequest.
        :rtype: IntervalPeriod
        """
        return self._interval_period

    @interval_period.setter
    def interval_period(self, interval_period: IntervalPeriod):
        """Sets the interval_period of this EventRequest.


        :param interval_period: The interval_period of this EventRequest.
        :type interval_period: IntervalPeriod
        """

        self._interval_period = interval_period

    @property
    def intervals(self) -> List[Interval]:
        """Gets the intervals of this EventRequest.

        A list of interval objects.  # noqa: E501

        :return: The intervals of this EventRequest.
        :rtype: List[Interval]
        """
        return self._intervals

    @intervals.setter
    def intervals(self, intervals: List[Interval]):
        """Sets the intervals of this EventRequest.

        A list of interval objects.  # noqa: E501

        :param intervals: The intervals of this EventRequest.
        :type intervals: List[Interval]
        """

        self._intervals = intervals
