# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IntervalPeriod(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start: str='None', duration: str='None', randomize_start: str='None'):  # noqa: E501
        """IntervalPeriod - a model defined in Swagger

        :param start: The start of this IntervalPeriod.  # noqa: E501
        :type start: str
        :param duration: The duration of this IntervalPeriod.  # noqa: E501
        :type duration: str
        :param randomize_start: The randomize_start of this IntervalPeriod.  # noqa: E501
        :type randomize_start: str
        """
        self.swagger_types = {
            'start': str,
            'duration': str,
            'randomize_start': str
        }

        self.attribute_map = {
            'start': 'start',
            'duration': 'duration',
            'randomize_start': 'randomizeStart'
        }
        self._start = start
        self._duration = duration
        self._randomize_start = randomize_start

    @classmethod
    def from_dict(cls, dikt) -> 'IntervalPeriod':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The intervalPeriod of this IntervalPeriod.  # noqa: E501
        :rtype: IntervalPeriod
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start(self) -> str:
        """Gets the start of this IntervalPeriod.

        The start time of an interval or set of intervals.  # noqa: E501

        :return: The start of this IntervalPeriod.
        :rtype: str
        """
        return self._start

    @start.setter
    def start(self, start: str):
        """Sets the start of this IntervalPeriod.

        The start time of an interval or set of intervals.  # noqa: E501

        :param start: The start of this IntervalPeriod.
        :type start: str
        """

        self._start = start

    @property
    def duration(self) -> str:
        """Gets the duration of this IntervalPeriod.

        The duration of an interval or set of intervals.  # noqa: E501

        :return: The duration of this IntervalPeriod.
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration: str):
        """Sets the duration of this IntervalPeriod.

        The duration of an interval or set of intervals.  # noqa: E501

        :param duration: The duration of this IntervalPeriod.
        :type duration: str
        """

        self._duration = duration

    @property
    def randomize_start(self) -> str:
        """Gets the randomize_start of this IntervalPeriod.

        Indicates a randomization time that may be applied to start.  # noqa: E501

        :return: The randomize_start of this IntervalPeriod.
        :rtype: str
        """
        return self._randomize_start

    @randomize_start.setter
    def randomize_start(self, randomize_start: str):
        """Sets the randomize_start of this IntervalPeriod.

        Indicates a randomization time that may be applied to start.  # noqa: E501

        :param randomize_start: The randomize_start of this IntervalPeriod.
        :type randomize_start: str
        """

        self._randomize_start = randomize_start
