# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MqttNotifierAuthenticationAnonymous(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, method: str=None):  # noqa: E501
        """MqttNotifierAuthenticationAnonymous - a model defined in Swagger

        :param method: The method of this MqttNotifierAuthenticationAnonymous.  # noqa: E501
        :type method: str
        """
        self.swagger_types = {
            'method': str
        }

        self.attribute_map = {
            'method': 'method'
        }
        self._method = method

    @classmethod
    def from_dict(cls, dikt) -> 'MqttNotifierAuthenticationAnonymous':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The mqttNotifierAuthenticationAnonymous of this MqttNotifierAuthenticationAnonymous.  # noqa: E501
        :rtype: MqttNotifierAuthenticationAnonymous
        """
        return util.deserialize_model(dikt, cls)

    @property
    def method(self) -> str:
        """Gets the method of this MqttNotifierAuthenticationAnonymous.

        Specifies anonymous authentication  # noqa: E501

        :return: The method of this MqttNotifierAuthenticationAnonymous.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method: str):
        """Sets the method of this MqttNotifierAuthenticationAnonymous.

        Specifies anonymous authentication  # noqa: E501

        :param method: The method of this MqttNotifierAuthenticationAnonymous.
        :type method: str
        """
        allowed_values = ["ANONYMOUS"]  # noqa: E501
        if method not in allowed_values:
            raise ValueError(
                "Invalid value for `method` ({0}), must be one of {1}"
                .format(method, allowed_values)
            )

        self._method = method
