# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.one_ofmqtt_notifier_binding_object_authentication import OneOfmqttNotifierBindingObjectAuthentication  # noqa: F401,E501
from swagger_server import util


class MqttNotifierBindingObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, uris: List[str]=None, serialization: str=None, authentication: OneOfmqttNotifierBindingObjectAuthentication=None):  # noqa: E501
        """MqttNotifierBindingObject - a model defined in Swagger

        :param uris: The uris of this MqttNotifierBindingObject.  # noqa: E501
        :type uris: List[str]
        :param serialization: The serialization of this MqttNotifierBindingObject.  # noqa: E501
        :type serialization: str
        :param authentication: The authentication of this MqttNotifierBindingObject.  # noqa: E501
        :type authentication: OneOfmqttNotifierBindingObjectAuthentication
        """
        self.swagger_types = {
            'uris': List[str],
            'serialization': str,
            'authentication': OneOfmqttNotifierBindingObjectAuthentication
        }

        self.attribute_map = {
            'uris': 'URIS',
            'serialization': 'serialization',
            'authentication': 'authentication'
        }
        self._uris = uris
        self._serialization = serialization
        self._authentication = authentication

    @classmethod
    def from_dict(cls, dikt) -> 'MqttNotifierBindingObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The mqttNotifierBindingObject of this MqttNotifierBindingObject.  # noqa: E501
        :rtype: MqttNotifierBindingObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uris(self) -> List[str]:
        """Gets the uris of this MqttNotifierBindingObject.


        :return: The uris of this MqttNotifierBindingObject.
        :rtype: List[str]
        """
        return self._uris

    @uris.setter
    def uris(self, uris: List[str]):
        """Sets the uris of this MqttNotifierBindingObject.


        :param uris: The uris of this MqttNotifierBindingObject.
        :type uris: List[str]
        """
        if uris is None:
            raise ValueError("Invalid value for `uris`, must not be `None`")  # noqa: E501

        self._uris = uris

    @property
    def serialization(self) -> str:
        """Gets the serialization of this MqttNotifierBindingObject.

        Currently always JSON, perhaps other formats supported in future  # noqa: E501

        :return: The serialization of this MqttNotifierBindingObject.
        :rtype: str
        """
        return self._serialization

    @serialization.setter
    def serialization(self, serialization: str):
        """Sets the serialization of this MqttNotifierBindingObject.

        Currently always JSON, perhaps other formats supported in future  # noqa: E501

        :param serialization: The serialization of this MqttNotifierBindingObject.
        :type serialization: str
        """
        allowed_values = ["JSON"]  # noqa: E501
        if serialization not in allowed_values:
            raise ValueError(
                "Invalid value for `serialization` ({0}), must be one of {1}"
                .format(serialization, allowed_values)
            )

        self._serialization = serialization

    @property
    def authentication(self) -> OneOfmqttNotifierBindingObjectAuthentication:
        """Gets the authentication of this MqttNotifierBindingObject.


        :return: The authentication of this MqttNotifierBindingObject.
        :rtype: OneOfmqttNotifierBindingObjectAuthentication
        """
        return self._authentication

    @authentication.setter
    def authentication(self, authentication: OneOfmqttNotifierBindingObjectAuthentication):
        """Sets the authentication of this MqttNotifierBindingObject.


        :param authentication: The authentication of this MqttNotifierBindingObject.
        :type authentication: OneOfmqttNotifierBindingObjectAuthentication
        """
        if authentication is None:
            raise ValueError("Invalid value for `authentication`, must not be `None`")  # noqa: E501

        self._authentication = authentication
