# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MqttNotifierAuthenticationOauth2BearerToken(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, method: str=None, username: str=None, password: str=None):  # noqa: E501
        """MqttNotifierAuthenticationOauth2BearerToken - a model defined in Swagger

        :param method: The method of this MqttNotifierAuthenticationOauth2BearerToken.  # noqa: E501
        :type method: str
        :param username: The username of this MqttNotifierAuthenticationOauth2BearerToken.  # noqa: E501
        :type username: str
        :param password: The password of this MqttNotifierAuthenticationOauth2BearerToken.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'method': str,
            'username': str,
            'password': str
        }

        self.attribute_map = {
            'method': 'method',
            'username': 'username',
            'password': 'password'
        }
        self._method = method
        self._username = username
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'MqttNotifierAuthenticationOauth2BearerToken':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The mqttNotifierAuthenticationOauth2BearerToken of this MqttNotifierAuthenticationOauth2BearerToken.  # noqa: E501
        :rtype: MqttNotifierAuthenticationOauth2BearerToken
        """
        return util.deserialize_model(dikt, cls)

    @property
    def method(self) -> str:
        """Gets the method of this MqttNotifierAuthenticationOauth2BearerToken.

        Specifies OAuth2 bearer token authentication  # noqa: E501

        :return: The method of this MqttNotifierAuthenticationOauth2BearerToken.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method: str):
        """Sets the method of this MqttNotifierAuthenticationOauth2BearerToken.

        Specifies OAuth2 bearer token authentication  # noqa: E501

        :param method: The method of this MqttNotifierAuthenticationOauth2BearerToken.
        :type method: str
        """
        allowed_values = ["OAUTH2_BEARER_TOKEN"]  # noqa: E501
        if method not in allowed_values:
            raise ValueError(
                "Invalid value for `method` ({0}), must be one of {1}"
                .format(method, allowed_values)
            )

        self._method = method

    @property
    def username(self) -> str:
        """Gets the username of this MqttNotifierAuthenticationOauth2BearerToken.

        Either the distinguished string \"{clientID}\", or any other literal string  # noqa: E501

        :return: The username of this MqttNotifierAuthenticationOauth2BearerToken.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this MqttNotifierAuthenticationOauth2BearerToken.

        Either the distinguished string \"{clientID}\", or any other literal string  # noqa: E501

        :param username: The username of this MqttNotifierAuthenticationOauth2BearerToken.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this MqttNotifierAuthenticationOauth2BearerToken.

        :return: The password of this MqttNotifierAuthenticationOauth2BearerToken.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this MqttNotifierAuthenticationOauth2BearerToken.

        :param password: The password of this MqttNotifierAuthenticationOauth2BearerToken.
        :type password: str
        """
        self._password = password
