# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MqttNotifierAuthenticationCertificate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, method: str=None, ca_cert: str=None, client_cert: str=None, client_key: str=None):  # noqa: E501
        """MqttNotifierAuthenticationCertificate - a model defined in Swagger

        :param method: The method of this MqttNotifierAuthenticationCertificate.  # noqa: E501
        :type method: str
        :param ca_cert: The ca_cert of this MqttNotifierAuthenticationCertificate.  # noqa: E501
        :type ca_cert: str
        :param client_cert: The client_cert of this MqttNotifierAuthenticationCertificate.  # noqa: E501
        :type client_cert: str
        :param client_key: The client_key of this MqttNotifierAuthenticationCertificate.  # noqa: E501
        :type client_key: str
        """
        self.swagger_types = {
            'method': str,
            'ca_cert': str,
            'client_cert': str,
            'client_key': str
        }

        self.attribute_map = {
            'method': 'method',
            'ca_cert': 'caCert',
            'client_cert': 'clientCert',
            'client_key': 'clientKey'
        }
        self._method = method
        self._ca_cert = ca_cert
        self._client_cert = client_cert
        self._client_key = client_key

    @classmethod
    def from_dict(cls, dikt) -> 'MqttNotifierAuthenticationCertificate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The mqttNotifierAuthenticationCertificate of this MqttNotifierAuthenticationCertificate.  # noqa: E501
        :rtype: MqttNotifierAuthenticationCertificate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def method(self) -> str:
        """Gets the method of this MqttNotifierAuthenticationCertificate.

        Specifies certificate authentication  # noqa: E501

        :return: The method of this MqttNotifierAuthenticationCertificate.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method: str):
        """Sets the method of this MqttNotifierAuthenticationCertificate.

        Specifies certificate authentication  # noqa: E501

        :param method: The method of this MqttNotifierAuthenticationCertificate.
        :type method: str
        """
        allowed_values = ["CERTIFICATE"]  # noqa: E501
        if method not in allowed_values:
            raise ValueError(
                "Invalid value for `method` ({0}), must be one of {1}"
                .format(method, allowed_values)
            )

        self._method = method

    @property
    def ca_cert(self) -> str:
        """Gets the ca_cert of this MqttNotifierAuthenticationCertificate.

        String containing the Certificate Authority certificate  # noqa: E501

        :return: The ca_cert of this MqttNotifierAuthenticationCertificate.
        :rtype: str
        """
        return self._ca_cert

    @ca_cert.setter
    def ca_cert(self, ca_cert: str):
        """Sets the ca_cert of this MqttNotifierAuthenticationCertificate.

        String containing the Certificate Authority certificate  # noqa: E501

        :param ca_cert: The ca_cert of this MqttNotifierAuthenticationCertificate.
        :type ca_cert: str
        """
        if ca_cert is None:
            raise ValueError("Invalid value for `ca_cert`, must not be `None`")  # noqa: E501

        self._ca_cert = ca_cert

    @property
    def client_cert(self) -> str:
        """Gets the client_cert of this MqttNotifierAuthenticationCertificate.

        String containing the Client certificate  # noqa: E501

        :return: The client_cert of this MqttNotifierAuthenticationCertificate.
        :rtype: str
        """
        return self._client_cert

    @client_cert.setter
    def client_cert(self, client_cert: str):
        """Sets the client_cert of this MqttNotifierAuthenticationCertificate.

        String containing the Client certificate  # noqa: E501

        :param client_cert: The client_cert of this MqttNotifierAuthenticationCertificate.
        :type client_cert: str
        """
        if client_cert is None:
            raise ValueError("Invalid value for `client_cert`, must not be `None`")  # noqa: E501

        self._client_cert = client_cert

    @property
    def client_key(self) -> str:
        """Gets the client_key of this MqttNotifierAuthenticationCertificate.

        String containing the client certificate private key  # noqa: E501

        :return: The client_key of this MqttNotifierAuthenticationCertificate.
        :rtype: str
        """
        return self._client_key

    @client_key.setter
    def client_key(self, client_key: str):
        """Sets the client_key of this MqttNotifierAuthenticationCertificate.

        String containing the client certificate private key  # noqa: E501

        :param client_key: The client_key of this MqttNotifierAuthenticationCertificate.
        :type client_key: str
        """
        if client_key is None:
            raise ValueError("Invalid value for `client_key`, must not be `None`")  # noqa: E501

        self._client_key = client_key
