# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.notifier_operations_topics import NotifierOperationsTopics  # noqa: F401,E501
from swagger_server import util


class NotifierTopicsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, topics: NotifierOperationsTopics=None):  # noqa: E501
        """NotifierTopicsResponse - a model defined in Swagger

        :param topics: The topics of this NotifierTopicsResponse.  # noqa: E501
        :type topics: NotifierOperationsTopics
        """
        self.swagger_types = {
            'topics': NotifierOperationsTopics
        }

        self.attribute_map = {
            'topics': 'topics'
        }
        self._topics = topics

    @classmethod
    def from_dict(cls, dikt) -> 'NotifierTopicsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The notifierTopicsResponse of this NotifierTopicsResponse.  # noqa: E501
        :rtype: NotifierTopicsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def topics(self) -> NotifierOperationsTopics:
        """Gets the topics of this NotifierTopicsResponse.


        :return: The topics of this NotifierTopicsResponse.
        :rtype: NotifierOperationsTopics
        """
        return self._topics

    @topics.setter
    def topics(self, topics: NotifierOperationsTopics):
        """Sets the topics of this NotifierTopicsResponse.


        :param topics: The topics of this NotifierTopicsResponse.
        :type topics: NotifierOperationsTopics
        """
        if topics is None:
            raise ValueError("Invalid value for `topics`, must not be `None`")  # noqa: E501

        self._topics = topics
