# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NotifierOperationsTopics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, create: str=None, update: str=None, delete: str=None, all: str=None):  # noqa: E501
        """NotifierOperationsTopics - a model defined in Swagger

        :param create: The create of this NotifierOperationsTopics.  # noqa: E501
        :type create: str
        :param update: The update of this NotifierOperationsTopics.  # noqa: E501
        :type update: str
        :param delete: The delete of this NotifierOperationsTopics.  # noqa: E501
        :type delete: str
        :param all: The all of this NotifierOperationsTopics.  # noqa: E501
        :type all: str
        """
        self.swagger_types = {
            'create': str,
            'update': str,
            'delete': str,
            'all': str
        }

        self.attribute_map = {
            'create': 'CREATE',
            'update': 'UPDATE',
            'delete': 'DELETE',
            'all': 'ALL'
        }
        self._create = create
        self._update = update
        self._delete = delete
        self._all = all

    @classmethod
    def from_dict(cls, dikt) -> 'NotifierOperationsTopics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The notifierOperationsTopics of this NotifierOperationsTopics.  # noqa: E501
        :rtype: NotifierOperationsTopics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def create(self) -> str:
        """Gets the create of this NotifierOperationsTopics.

        'Topic path for CREATE operations,  not provided for notifications for a specific object ID,  e.g. until programID foo is created, clients unable to  request notifications of its creation!'   # noqa: E501

        :return: The create of this NotifierOperationsTopics.
        :rtype: str
        """
        return self._create

    @create.setter
    def create(self, create: str):
        """Sets the create of this NotifierOperationsTopics.

        'Topic path for CREATE operations,  not provided for notifications for a specific object ID,  e.g. until programID foo is created, clients unable to  request notifications of its creation!'   # noqa: E501

        :param create: The create of this NotifierOperationsTopics.
        :type create: str
        """

        self._create = create

    @property
    def update(self) -> str:
        """Gets the update of this NotifierOperationsTopics.

        Topic path for UPDATE operations  # noqa: E501

        :return: The update of this NotifierOperationsTopics.
        :rtype: str
        """
        return self._update

    @update.setter
    def update(self, update: str):
        """Sets the update of this NotifierOperationsTopics.

        Topic path for UPDATE operations  # noqa: E501

        :param update: The update of this NotifierOperationsTopics.
        :type update: str
        """
        if update is None:
            raise ValueError("Invalid value for `update`, must not be `None`")  # noqa: E501

        self._update = update

    @property
    def delete(self) -> str:
        """Gets the delete of this NotifierOperationsTopics.

        Topic path for DELETE operations  # noqa: E501

        :return: The delete of this NotifierOperationsTopics.
        :rtype: str
        """
        return self._delete

    @delete.setter
    def delete(self, delete: str):
        """Sets the delete of this NotifierOperationsTopics.

        Topic path for DELETE operations  # noqa: E501

        :param delete: The delete of this NotifierOperationsTopics.
        :type delete: str
        """
        if delete is None:
            raise ValueError("Invalid value for `delete`, must not be `None`")  # noqa: E501

        self._delete = delete

    @property
    def all(self) -> str:
        """Gets the all of this NotifierOperationsTopics.

        Topic path for ALL operations, if supported by VTN  # noqa: E501

        :return: The all of this NotifierOperationsTopics.
        :rtype: str
        """
        return self._all

    @all.setter
    def all(self, all: str):
        """Sets the all of this NotifierOperationsTopics.

        Topic path for ALL operations, if supported by VTN  # noqa: E501

        :param all: The all of this NotifierOperationsTopics.
        :type all: str
        """

        self._all = all
