# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.one_ofnotification_object import OneOfnotificationObject  # noqa: F401,E501
from swagger_server import util


class Notification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, object_type: str=None, operation: str=None, object: OneOfnotificationObject=None):  # noqa: E501
        """Notification - a model defined in Swagger

        :param object_type: The object_type of this Notification.  # noqa: E501
        :type object_type: str
        :param operation: The operation of this Notification.  # noqa: E501
        :type operation: str
        :param object: The object of this Notification.  # noqa: E501
        :type object: OneOfnotificationObject
        """
        self.swagger_types = {
            'object_type': str,
            'operation': str,
            'object': OneOfnotificationObject
        }

        self.attribute_map = {
            'object_type': 'objectType',
            'operation': 'operation',
            'object': 'object'
        }
        self._object_type = object_type
        self._operation = operation
        self._object = object

    @classmethod
    def from_dict(cls, dikt) -> 'Notification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The notification of this Notification.  # noqa: E501
        :rtype: Notification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def object_type(self) -> str:
        """Gets the object_type of this Notification.

        type of object being returned, i.e. PROGRAM, EVENT, REPORT.  # noqa: E501

        :return: The object_type of this Notification.
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type: str):
        """Sets the object_type of this Notification.

        type of object being returned, i.e. PROGRAM, EVENT, REPORT.  # noqa: E501

        :param object_type: The object_type of this Notification.
        :type object_type: str
        """
        allowed_values = ["PROGRAM", "EVENT", "REPORT", "SUBSCRIPTION", "VEN", "RESOURCE"]  # noqa: E501
        if object_type not in allowed_values:
            raise ValueError(
                "Invalid value for `object_type` ({0}), must be one of {1}"
                .format(object_type, allowed_values)
            )

        self._object_type = object_type

    @property
    def operation(self) -> str:
        """Gets the operation of this Notification.

        the operation on on object that triggered the notification.  # noqa: E501

        :return: The operation of this Notification.
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation: str):
        """Sets the operation of this Notification.

        the operation on on object that triggered the notification.  # noqa: E501

        :param operation: The operation of this Notification.
        :type operation: str
        """
        allowed_values = ["POST", "PUT", "DELETE"]  # noqa: E501
        if operation not in allowed_values:
            raise ValueError(
                "Invalid value for `operation` ({0}), must be one of {1}"
                .format(operation, allowed_values)
            )

        self._operation = operation

    @property
    def object(self) -> OneOfnotificationObject:
        """Gets the object of this Notification.

        the object that is the subject of the notification.  # noqa: E501

        :return: The object of this Notification.
        :rtype: OneOfnotificationObject
        """
        return self._object

    @object.setter
    def object(self, object: OneOfnotificationObject):
        """Sets the object of this Notification.

        the object that is the subject of the notification.  # noqa: E501

        :param object: The object of this Notification.
        :type object: OneOfnotificationObject
        """

        self._object = object
