# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.mqtt_notifier_binding_object import MqttNotifierBindingObject  # noqa: F401,E501
from swagger_server import util


class NotifiersResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, webhook: bool=None, mqtt: MqttNotifierBindingObject=None):  # noqa: E501
        """NotifiersResponse - a model defined in Swagger

        :param webhook: The webhook of this NotifiersResponse.  # noqa: E501
        :type webhook: bool
        :param mqtt: The mqtt of this NotifiersResponse.  # noqa: E501
        :type mqtt: MqttNotifierBindingObject
        """
        self.swagger_types = {
            'webhook': bool,
            'mqtt': MqttNotifierBindingObject
        }

        self.attribute_map = {
            'webhook': 'WEBHOOK',
            'mqtt': 'MQTT'
        }
        self._webhook = webhook
        self._mqtt = mqtt

    @classmethod
    def from_dict(cls, dikt) -> 'NotifiersResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The notifiersResponse of this NotifiersResponse.  # noqa: E501
        :rtype: NotifiersResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def webhook(self) -> bool:
        """Gets the webhook of this NotifiersResponse.

        Currently MUST be true  # noqa: E501

        :return: The webhook of this NotifiersResponse.
        :rtype: bool
        """
        return self._webhook

    @webhook.setter
    def webhook(self, webhook: bool):
        """Sets the webhook of this NotifiersResponse.

        Currently MUST be true  # noqa: E501

        :param webhook: The webhook of this NotifiersResponse.
        :type webhook: bool
        """
        if webhook is None:
            raise ValueError("Invalid value for `webhook`, must not be `None`")  # noqa: E501

        self._webhook = webhook

    @property
    def mqtt(self) -> MqttNotifierBindingObject:
        """Gets the mqtt of this NotifiersResponse.


        :return: The mqtt of this NotifiersResponse.
        :rtype: MqttNotifierBindingObject
        """
        return self._mqtt

    @mqtt.setter
    def mqtt(self, mqtt: MqttNotifierBindingObject):
        """Sets the mqtt of this NotifiersResponse.


        :param mqtt: The mqtt of this NotifiersResponse.
        :type mqtt: MqttNotifierBindingObject
        """

        self._mqtt = mqtt
