# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.model_date_time import ModelDateTime  # noqa: F401,E501
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.object_types import ObjectTypes  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class ObjectMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: ObjectID=None, created_date_time: ModelDateTime=None, modification_date_time: ModelDateTime=None, object_type: ObjectTypes=None):  # noqa: E501
        """ObjectMetadata - a model defined in Swagger

        :param id: The id of this ObjectMetadata.  # noqa: E501
        :type id: ObjectID
        :param created_date_time: The created_date_time of this ObjectMetadata.  # noqa: E501
        :type created_date_time: ModelDateTime
        :param modification_date_time: The modification_date_time of this ObjectMetadata.  # noqa: E501
        :type modification_date_time: ModelDateTime
        :param object_type: The object_type of this ObjectMetadata.  # noqa: E501
        :type object_type: ObjectTypes
        """
        self.swagger_types = {
            'id': ObjectID,
            'created_date_time': ModelDateTime,
            'modification_date_time': ModelDateTime,
            'object_type': ObjectTypes
        }

        self.attribute_map = {
            'id': 'id',
            'created_date_time': 'createdDateTime',
            'modification_date_time': 'modificationDateTime',
            'object_type': 'objectType'
        }
        self._id = id
        self._created_date_time = created_date_time
        self._modification_date_time = modification_date_time
        self._object_type = object_type

    @classmethod
    def from_dict(cls, dikt) -> 'ObjectMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The object_metadata of this ObjectMetadata.  # noqa: E501
        :rtype: ObjectMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> ObjectID:
        """Gets the id of this ObjectMetadata.


        :return: The id of this ObjectMetadata.
        :rtype: ObjectID
        """
        return self._id

    @id.setter
    def id(self, id: ObjectID):
        """Sets the id of this ObjectMetadata.


        :param id: The id of this ObjectMetadata.
        :type id: ObjectID
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def created_date_time(self) -> ModelDateTime:
        """Gets the created_date_time of this ObjectMetadata.


        :return: The created_date_time of this ObjectMetadata.
        :rtype: ModelDateTime
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time: ModelDateTime):
        """Sets the created_date_time of this ObjectMetadata.


        :param created_date_time: The created_date_time of this ObjectMetadata.
        :type created_date_time: ModelDateTime
        """
        if created_date_time is None:
            raise ValueError("Invalid value for `created_date_time`, must not be `None`")  # noqa: E501

        self._created_date_time = created_date_time

    @property
    def modification_date_time(self) -> ModelDateTime:
        """Gets the modification_date_time of this ObjectMetadata.


        :return: The modification_date_time of this ObjectMetadata.
        :rtype: ModelDateTime
        """
        return self._modification_date_time

    @modification_date_time.setter
    def modification_date_time(self, modification_date_time: ModelDateTime):
        """Sets the modification_date_time of this ObjectMetadata.


        :param modification_date_time: The modification_date_time of this ObjectMetadata.
        :type modification_date_time: ModelDateTime
        """
        if modification_date_time is None:
            raise ValueError("Invalid value for `modification_date_time`, must not be `None`")  # noqa: E501

        self._modification_date_time = modification_date_time

    @property
    def object_type(self) -> ObjectTypes:
        """Gets the object_type of this ObjectMetadata.


        :return: The object_type of this ObjectMetadata.
        :rtype: ObjectTypes
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type: ObjectTypes):
        """Sets the object_type of this ObjectMetadata.


        :param object_type: The object_type of this ObjectMetadata.
        :type object_type: ObjectTypes
        """
        if object_type is None:
            raise ValueError("Invalid value for `object_type`, must not be `None`")  # noqa: E501

        self._object_type = object_type
