# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.one_ofpayload_values_items import OneOfpayloadValuesItems  # noqa: F401,E501
from swagger_server import util


class Payload(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, payload_type: str='None', values: List[OneOfpayloadValuesItems]=None):  # noqa: E501
        """Payload - a model defined in Swagger

        :param payload_type: The payload_type of this Payload.  # noqa: E501
        :type payload_type: str
        :param values: The values of this Payload.  # noqa: E501
        :type values: List[OneOfpayloadValuesItems]
        """
        self.swagger_types = {
            'payload_type': str,
            'values': List[OneOfpayloadValuesItems]
        }

        self.attribute_map = {
            'payload_type': 'payloadType',
            'values': 'values'
        }
        self._payload_type = payload_type
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'Payload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The payload of this Payload.  # noqa: E501
        :rtype: Payload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payload_type(self) -> str:
        """Gets the payload_type of this Payload.

        Enumerated or private string signifying the nature of values. For example, \"PRICE\" indicates value is to be interpreted as a currency.   # noqa: E501

        :return: The payload_type of this Payload.
        :rtype: str
        """
        return self._payload_type

    @payload_type.setter
    def payload_type(self, payload_type: str):
        """Sets the payload_type of this Payload.

        Enumerated or private string signifying the nature of values. For example, \"PRICE\" indicates value is to be interpreted as a currency.   # noqa: E501

        :param payload_type: The payload_type of this Payload.
        :type payload_type: str
        """
        if payload_type is None:
            raise ValueError("Invalid value for `payload_type`, must not be `None`")  # noqa: E501

        self._payload_type = payload_type

    @property
    def values(self) -> List[OneOfpayloadValuesItems]:
        """Gets the values of this Payload.

        A sequence of data points. Most often a singular value such as a price.  # noqa: E501

        :return: The values of this Payload.
        :rtype: List[OneOfpayloadValuesItems]
        """
        return self._values

    @values.setter
    def values(self, values: List[OneOfpayloadValuesItems]):
        """Sets the values of this Payload.

        A sequence of data points. Most often a singular value such as a price.  # noqa: E501

        :param values: The values of this Payload.
        :type values: List[OneOfpayloadValuesItems]
        """
        if values is None:
            raise ValueError("Invalid value for `values`, must not be `None`")  # noqa: E501

        self._values = values
