# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.interval_period import IntervalPeriod  # noqa: F401,E501
from swagger_server.models.model_date_time import ModelDateTime  # noqa: F401,E501
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.object_metadata import ObjectMetadata  # noqa: F401,E501
from swagger_server.models.object_types import ObjectTypes  # noqa: F401,E501
from swagger_server.models.program_request import ProgramRequest  # noqa: F401,E501
from swagger_server.models.program_request_program_descriptions import ProgramRequestProgramDescriptions  # noqa: F401,E501
from swagger_server.models.any_ofprogram_request_payload_descriptors_items import AnyOfprogramRequestPayloadDescriptorsItems
from swagger_server.models.target import Target  # noqa: F401,E501
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class Program(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, program_name: str=None, interval_period: IntervalPeriod=None, program_descriptions: List[ProgramRequestProgramDescriptions]=None, payload_descriptors: List[AnyOfprogramRequestPayloadDescriptorsItems]=None, attributes: List[ValuesMap]=None, targets: List[str]=None, id: ObjectID=None, created_date_time: ModelDateTime=None, modification_date_time: ModelDateTime=None, object_type: ObjectTypes=None):  # noqa: E501
        """Program - a model defined in Swagger

        :param program_name: The program_name of this Program.  # noqa: E501
        :type program_name: str
        :param interval_period: The interval_period of this Program.  # noqa: E501
        :type interval_period: IntervalPeriod
        :param program_descriptions: The program_descriptions of this Program.  # noqa: E501
        :type program_descriptions: List[ProgramRequestProgramDescriptions]
        :param payload_descriptors: The payload_descriptors of this Program.  # noqa: E501
        :type payload_descriptors: List[Object]
        :param attributes: The attributes of this Program.  # noqa: E501
        :type attributes: List[ValuesMap]
        :param targets: The targets of this Program.  # noqa: E501
        :type targets: List[Target]
        :param id: The id of this Program.  # noqa: E501
        :type id: ObjectID
        :param created_date_time: The created_date_time of this Program.  # noqa: E501
        :type created_date_time: ModelDateTime
        :param modification_date_time: The modification_date_time of this Program.  # noqa: E501
        :type modification_date_time: ModelDateTime
        :param object_type: The object_type of this Program.  # noqa: E501
        :type object_type: ObjectTypes
        """
        self.swagger_types = {
            'program_name': str,
            'interval_period': IntervalPeriod,
            'program_descriptions': List[ProgramRequestProgramDescriptions],
            'payload_descriptors': List[AnyOfprogramRequestPayloadDescriptorsItems],
            'attributes': List[ValuesMap],
            'targets': List[str],
            'id': ObjectID,
            'created_date_time': ModelDateTime,
            'modification_date_time': ModelDateTime,
            'object_type': ObjectTypes
        }

        self.attribute_map = {
            'program_name': 'programName',
            'interval_period': 'intervalPeriod',
            'program_descriptions': 'programDescriptions',
            'payload_descriptors': 'payloadDescriptors',
            'attributes': 'attributes',
            'targets': 'targets',
            'id': 'id',
            'created_date_time': 'createdDateTime',
            'modification_date_time': 'modificationDateTime',
            'object_type': 'objectType'
        }
        self._program_name = program_name
        self._interval_period = interval_period
        self._program_descriptions = program_descriptions
        self._payload_descriptors = payload_descriptors
        self._attributes = attributes
        self._targets = targets
        self._id = id
        self._created_date_time = created_date_time
        self._modification_date_time = modification_date_time
        self._object_type = object_type

    @classmethod
    def from_dict(cls, dikt) -> 'Program':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The program of this Program.  # noqa: E501
        :rtype: Program
        """
        return util.deserialize_model(dikt, cls)

    @property
    def program_name(self) -> str:
        """Gets the program_name of this Program.

        Short name to uniquely identify program.  # noqa: E501

        :return: The program_name of this Program.
        :rtype: str
        """
        return self._program_name

    @program_name.setter
    def program_name(self, program_name: str):
        """Sets the program_name of this Program.

        Short name to uniquely identify program.  # noqa: E501

        :param program_name: The program_name of this Program.
        :type program_name: str
        """
        if program_name is None:
            raise ValueError("Invalid value for `program_name`, must not be `None`")  # noqa: E501

        self._program_name = program_name

    @property
    def interval_period(self) -> IntervalPeriod:
        """Gets the interval_period of this Program.


        :return: The interval_period of this Program.
        :rtype: IntervalPeriod
        """
        return self._interval_period

    @interval_period.setter
    def interval_period(self, interval_period: IntervalPeriod):
        """Sets the interval_period of this Program.


        :param interval_period: The interval_period of this Program.
        :type interval_period: IntervalPeriod
        """

        self._interval_period = interval_period

    @property
    def program_descriptions(self) -> List[ProgramRequestProgramDescriptions]:
        """Gets the program_descriptions of this Program.

        A list of programDescriptions  # noqa: E501

        :return: The program_descriptions of this Program.
        :rtype: List[ProgramRequestProgramDescriptions]
        """
        return self._program_descriptions

    @program_descriptions.setter
    def program_descriptions(self, program_descriptions: List[ProgramRequestProgramDescriptions]):
        """Sets the program_descriptions of this Program.

        A list of programDescriptions  # noqa: E501

        :param program_descriptions: The program_descriptions of this Program.
        :type program_descriptions: List[ProgramRequestProgramDescriptions]
        """

        self._program_descriptions = program_descriptions

    @property
    def payload_descriptors(self) -> List[AnyOfprogramRequestPayloadDescriptorsItems]:
        """Gets the payload_descriptors of this Program.

        A list of payloadDescriptors.  # noqa: E501

        :return: The payload_descriptors of this Program.
        :rtype: List[AnyOfprogramRequestPayloadDescriptorsItems]
        """
        return self._payload_descriptors

    @payload_descriptors.setter
    def payload_descriptors(self, payload_descriptors: List[AnyOfprogramRequestPayloadDescriptorsItems]):
        """Sets the payload_descriptors of this Program.

        A list of payloadDescriptors.  # noqa: E501

        :param payload_descriptors: The payload_descriptors of this Program.
        :type payload_descriptors: List[AnyOfprogramRequestPayloadDescriptorsItems]
        """

        self._payload_descriptors = payload_descriptors

    @property
    def attributes(self) -> List[ValuesMap]:
        """Gets the attributes of this Program.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :return: The attributes of this Program.
        :rtype: List[ValuesMap]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[ValuesMap]):
        """Sets the attributes of this Program.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :param attributes: The attributes of this Program.
        :type attributes: List[ValuesMap]
        """

        self._attributes = attributes

    @property
    def targets(self) -> List[Target]:
        """Gets the targets of this Program.

        A list of targets.  # noqa: E501

        :return: The targets of this Program.
        :rtype: List[Target]
        """
        return self._targets

    @targets.setter
    def targets(self, targets: List[Target]):
        """Sets the targets of this Program.

        A list of targets.  # noqa: E501

        :param targets: The targets of this Program.
        :type targets: List[Target]
        """

        self._targets = targets

    @property
    def id(self) -> ObjectID:
        """Gets the id of this Program.


        :return: The id of this Program.
        :rtype: ObjectID
        """
        return self._id

    @id.setter
    def id(self, id: ObjectID):
        """Sets the id of this Program.


        :param id: The id of this Program.
        :type id: ObjectID
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def created_date_time(self) -> ModelDateTime:
        """Gets the created_date_time of this Program.


        :return: The created_date_time of this Program.
        :rtype: ModelDateTime
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time: ModelDateTime):
        """Sets the created_date_time of this Program.


        :param created_date_time: The created_date_time of this Program.
        :type created_date_time: ModelDateTime
        """
        if created_date_time is None:
            raise ValueError("Invalid value for `created_date_time`, must not be `None`")  # noqa: E501

        self._created_date_time = created_date_time

    @property
    def modification_date_time(self) -> ModelDateTime:
        """Gets the modification_date_time of this Program.


        :return: The modification_date_time of this Program.
        :rtype: ModelDateTime
        """
        return self._modification_date_time

    @modification_date_time.setter
    def modification_date_time(self, modification_date_time: ModelDateTime):
        """Sets the modification_date_time of this Program.


        :param modification_date_time: The modification_date_time of this Program.
        :type modification_date_time: ModelDateTime
        """
        if modification_date_time is None:
            raise ValueError("Invalid value for `modification_date_time`, must not be `None`")  # noqa: E501

        self._modification_date_time = modification_date_time

    @property
    def object_type(self) -> ObjectTypes:
        """Gets the object_type of this Program.


        :return: The object_type of this Program.
        :rtype: ObjectTypes
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type: ObjectTypes):
        """Sets the object_type of this Program.


        :param object_type: The object_type of this Program.
        :type object_type: ObjectTypes
        """
        if object_type is None:
            raise ValueError("Invalid value for `object_type`, must not be `None`")  # noqa: E501

        self._object_type = object_type
