# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.interval_period import IntervalPeriod  # noqa: F401,E501
from swagger_server.models.program_request_program_descriptions import ProgramRequestProgramDescriptions  # noqa: F401,E501
from swagger_server.models.target import Target  # noqa: F401,E501
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
from swagger_server.models.any_ofprogram_request_payload_descriptors_items import AnyOfprogramRequestPayloadDescriptorsItems  # noqa: F401,E501
from swagger_server import util


class ProgramRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, program_name: str=None, interval_period: IntervalPeriod=None, program_descriptions: List[ProgramRequestProgramDescriptions]=None, payload_descriptors: List[AnyOfprogramRequestPayloadDescriptorsItems]=None, attributes: List[ValuesMap]=None, targets: List[Target]=None):  # noqa: E501
        """ProgramRequest - a model defined in Swagger

        :param program_name: The program_name of this ProgramRequest.  # noqa: E501
        :type program_name: str
        :param interval_period: The interval_period of this ProgramRequest.  # noqa: E501
        :type interval_period: IntervalPeriod
        :param program_descriptions: The program_descriptions of this ProgramRequest.  # noqa: E501
        :type program_descriptions: List[ProgramRequestProgramDescriptions]
        :param payload_descriptors: The payload_descriptors of this ProgramRequest.  # noqa: E501
        :type payload_descriptors: List[AnyOfprogramRequestPayloadDescriptorsItems]
        :param attributes: The attributes of this ProgramRequest.  # noqa: E501
        :type attributes: List[ValuesMap]
        :param targets: The targets of this ProgramRequest.  # noqa: E501
        :type targets: List[Target]
        """
        self.swagger_types = {
            'program_name': str,
            'interval_period': IntervalPeriod,
            'program_descriptions': List[ProgramRequestProgramDescriptions],
            'payload_descriptors': List[AnyOfprogramRequestPayloadDescriptorsItems],
            'attributes': List[ValuesMap],
            'targets': List[Target]
        }

        self.attribute_map = {
            'program_name': 'programName',
            'interval_period': 'intervalPeriod',
            'program_descriptions': 'programDescriptions',
            'payload_descriptors': 'payloadDescriptors',
            'attributes': 'attributes',
            'targets': 'targets'
        }
        self._program_name = program_name
        self._interval_period = interval_period
        self._program_descriptions = program_descriptions
        self._payload_descriptors = payload_descriptors
        self._attributes = attributes
        self._targets = targets

    @classmethod
    def from_dict(cls, dikt) -> 'ProgramRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The programRequest of this ProgramRequest.  # noqa: E501
        :rtype: ProgramRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def program_name(self) -> str:
        """Gets the program_name of this ProgramRequest.

        Short name to uniquely identify program.  # noqa: E501

        :return: The program_name of this ProgramRequest.
        :rtype: str
        """
        return self._program_name

    @program_name.setter
    def program_name(self, program_name: str):
        """Sets the program_name of this ProgramRequest.

        Short name to uniquely identify program.  # noqa: E501

        :param program_name: The program_name of this ProgramRequest.
        :type program_name: str
        """
        if program_name is None:
            raise ValueError("Invalid value for `program_name`, must not be `None`")  # noqa: E501

        self._program_name = program_name

    @property
    def interval_period(self) -> IntervalPeriod:
        """Gets the interval_period of this ProgramRequest.


        :return: The interval_period of this ProgramRequest.
        :rtype: IntervalPeriod
        """
        return self._interval_period

    @interval_period.setter
    def interval_period(self, interval_period: IntervalPeriod):
        """Sets the interval_period of this ProgramRequest.


        :param interval_period: The interval_period of this ProgramRequest.
        :type interval_period: IntervalPeriod
        """

        self._interval_period = interval_period

    @property
    def program_descriptions(self) -> List[ProgramRequestProgramDescriptions]:
        """Gets the program_descriptions of this ProgramRequest.

        A list of programDescriptions  # noqa: E501

        :return: The program_descriptions of this ProgramRequest.
        :rtype: List[ProgramRequestProgramDescriptions]
        """
        return self._program_descriptions

    @program_descriptions.setter
    def program_descriptions(self, program_descriptions: List[ProgramRequestProgramDescriptions]):
        """Sets the program_descriptions of this ProgramRequest.

        A list of programDescriptions  # noqa: E501

        :param program_descriptions: The program_descriptions of this ProgramRequest.
        :type program_descriptions: List[ProgramRequestProgramDescriptions]
        """

        self._program_descriptions = program_descriptions

    @property
    def payload_descriptors(self) -> List[AnyOfprogramRequestPayloadDescriptorsItems]:
        """Gets the payload_descriptors of this ProgramRequest.

        A list of payloadDescriptors.  # noqa: E501

        :return: The payload_descriptors of this ProgramRequest.
        :rtype: List[AnyOfprogramRequestPayloadDescriptorsItems]
        """
        return self._payload_descriptors

    @payload_descriptors.setter
    def payload_descriptors(self, payload_descriptors: List[AnyOfprogramRequestPayloadDescriptorsItems]):
        """Sets the payload_descriptors of this ProgramRequest.

        A list of payloadDescriptors.  # noqa: E501

        :param payload_descriptors: The payload_descriptors of this ProgramRequest.
        :type payload_descriptors: List[AnyOfprogramRequestPayloadDescriptorsItems]
        """

        self._payload_descriptors = payload_descriptors

    @property
    def attributes(self) -> List[ValuesMap]:
        """Gets the attributes of this ProgramRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :return: The attributes of this ProgramRequest.
        :rtype: List[ValuesMap]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[ValuesMap]):
        """Sets the attributes of this ProgramRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :param attributes: The attributes of this ProgramRequest.
        :type attributes: List[ValuesMap]
        """

        self._attributes = attributes

    @property
    def targets(self) -> List[Target]:
        """Gets the targets of this ProgramRequest.

        A list of targets.  # noqa: E501

        :return: The targets of this ProgramRequest.
        :rtype: List[Target]
        """
        return self._targets

    @targets.setter
    def targets(self, targets: List[Target]):
        """Sets the targets of this ProgramRequest.

        A list of targets.  # noqa: E501

        :param targets: The targets of this ProgramRequest.
        :type targets: List[Target]
        """

        self._targets = targets
