# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.interval import Interval  # noqa: F401,E501
from swagger_server.models.interval_period import IntervalPeriod  # noqa: F401,E501
from swagger_server.models.resource_name import ResourceName  # noqa: F401,E501
from swagger_server import util


class ReportRequestResources(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, resource_name: ResourceName=None, interval_period: IntervalPeriod=None, intervals: List[Interval]=None):  # noqa: E501
        """ReportRequestResources - a model defined in Swagger

        :param resource_name: The resource_name of this ReportRequestResources.  # noqa: E501
        :type resource_name: ResourceName
        :param interval_period: The interval_period of this ReportRequestResources.  # noqa: E501
        :type interval_period: IntervalPeriod
        :param intervals: The intervals of this ReportRequestResources.  # noqa: E501
        :type intervals: List[Interval]
        """
        self.swagger_types = {
            'resource_name': ResourceName,
            'interval_period': IntervalPeriod,
            'intervals': List[Interval]
        }

        self.attribute_map = {
            'resource_name': 'resourceName',
            'interval_period': 'intervalPeriod',
            'intervals': 'intervals'
        }
        self._resource_name = resource_name
        self._interval_period = interval_period
        self._intervals = intervals

    @classmethod
    def from_dict(cls, dikt) -> 'ReportRequestResources':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The reportRequest_resources of this ReportRequestResources.  # noqa: E501
        :rtype: ReportRequestResources
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resource_name(self) -> ResourceName:
        """Gets the resource_name of this ReportRequestResources.


        :return: The resource_name of this ReportRequestResources.
        :rtype: ResourceName
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name: ResourceName):
        """Sets the resource_name of this ReportRequestResources.


        :param resource_name: The resource_name of this ReportRequestResources.
        :type resource_name: ResourceName
        """
        if resource_name is None:
            raise ValueError("Invalid value for `resource_name`, must not be `None`")  # noqa: E501

        self._resource_name = resource_name

    @property
    def interval_period(self) -> IntervalPeriod:
        """Gets the interval_period of this ReportRequestResources.


        :return: The interval_period of this ReportRequestResources.
        :rtype: IntervalPeriod
        """
        return self._interval_period

    @interval_period.setter
    def interval_period(self, interval_period: IntervalPeriod):
        """Sets the interval_period of this ReportRequestResources.


        :param interval_period: The interval_period of this ReportRequestResources.
        :type interval_period: IntervalPeriod
        """

        self._interval_period = interval_period

    @property
    def intervals(self) -> List[Interval]:
        """Gets the intervals of this ReportRequestResources.

        A list of interval objects.  # noqa: E501

        :return: The intervals of this ReportRequestResources.
        :rtype: List[Interval]
        """
        return self._intervals

    @intervals.setter
    def intervals(self, intervals: List[Interval]):
        """Sets the intervals of this ReportRequestResources.

        A list of interval objects.  # noqa: E501

        :param intervals: The intervals of this ReportRequestResources.
        :type intervals: List[Interval]
        """
        if intervals is None:
            raise ValueError("Invalid value for `intervals`, must not be `None`")  # noqa: E501

        self._intervals = intervals
