# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.report_payload_descriptor import ReportPayloadDescriptor  # noqa: F401,E501
from swagger_server.models.report_request_resources import ReportRequestResources  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class ReportRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, program_id: ObjectID=None, event_id: ObjectID=None, client_name: str=None, report_name: str=None, payload_descriptors: List[ReportPayloadDescriptor]=None, resources: List[ReportRequestResources]=None):  # noqa: E501
        """ReportRequest - a model defined in Swagger

        :param program_id: The program_id of this ReportRequest.  # noqa: E501
        :type program_id: ObjectID
        :param event_id: The event_id of this ReportRequest.  # noqa: E501
        :type event_id: ObjectID
        :param client_name: The client_name of this ReportRequest.  # noqa: E501
        :type client_name: str
        :param report_name: The report_name of this ReportRequest.  # noqa: E501
        :type report_name: str
        :param payload_descriptors: The payload_descriptors of this ReportRequest.  # noqa: E501
        :type payload_descriptors: List[ReportPayloadDescriptor]
        :param resources: The resources of this ReportRequest.  # noqa: E501
        :type resources: List[ReportRequestResources]
        """
        self.swagger_types = {
            'program_id': ObjectID,
            'event_id': ObjectID,
            'client_name': str,
            'report_name': str,
            'payload_descriptors': List[ReportPayloadDescriptor],
            'resources': List[ReportRequestResources]
        }

        self.attribute_map = {
            'program_id': 'programID',
            'event_id': 'eventID',
            'client_name': 'clientName',
            'report_name': 'reportName',
            'payload_descriptors': 'payloadDescriptors',
            'resources': 'resources'
        }
        self._program_id = program_id
        self._event_id = event_id
        self._client_name = client_name
        self._report_name = report_name
        self._payload_descriptors = payload_descriptors
        self._resources = resources

    @classmethod
    def from_dict(cls, dikt) -> 'ReportRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The report_request of this ReportRequest.  # noqa: E501
        :rtype: ReportRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def program_id(self) -> ObjectID:
        """Gets the program_id of this ReportRequest.


        :return: The program_id of this ReportRequest.
        :rtype: ObjectID
        """
        return self._program_id

    @program_id.setter
    def program_id(self, program_id: ObjectID):
        """Sets the program_id of this ReportRequest.


        :param program_id: The program_id of this ReportRequest.
        :type program_id: ObjectID
        """
        if program_id is None:
            raise ValueError("Invalid value for `program_id`, must not be `None`")  # noqa: E501

        self._program_id = program_id

    @property
    def event_id(self) -> ObjectID:
        """Gets the event_id of this ReportRequest.


        :return: The event_id of this ReportRequest.
        :rtype: ObjectID
        """
        return self._event_id

    @event_id.setter
    def event_id(self, event_id: ObjectID):
        """Sets the event_id of this ReportRequest.


        :param event_id: The event_id of this ReportRequest.
        :type event_id: ObjectID
        """
        if event_id is None:
            raise ValueError("Invalid value for `event_id`, must not be `None`")  # noqa: E501

        self._event_id = event_id

    @property
    def client_name(self) -> str:
        """Gets the client_name of this ReportRequest.

        User generated identifier; may be VEN ID provisioned out-of-band.  # noqa: E501

        :return: The client_name of this ReportRequest.
        :rtype: str
        """
        return self._client_name

    @client_name.setter
    def client_name(self, client_name: str):
        """Sets the client_name of this ReportRequest.

        User generated identifier; may be VEN ID provisioned out-of-band.  # noqa: E501

        :param client_name: The client_name of this ReportRequest.
        :type client_name: str
        """
        if client_name is None:
            raise ValueError("Invalid value for `client_name`, must not be `None`")  # noqa: E501

        self._client_name = client_name

    @property
    def report_name(self) -> str:
        """Gets the report_name of this ReportRequest.

        User defined string for use in debugging or User Interface.  # noqa: E501

        :return: The report_name of this ReportRequest.
        :rtype: str
        """
        return self._report_name

    @report_name.setter
    def report_name(self, report_name: str):
        """Sets the report_name of this ReportRequest.

        User defined string for use in debugging or User Interface.  # noqa: E501

        :param report_name: The report_name of this ReportRequest.
        :type report_name: str
        """

        self._report_name = report_name

    @property
    def payload_descriptors(self) -> List[ReportPayloadDescriptor]:
        """Gets the payload_descriptors of this ReportRequest.

        A list of reportPayloadDescriptors.  # noqa: E501

        :return: The payload_descriptors of this ReportRequest.
        :rtype: List[ReportPayloadDescriptor]
        """
        return self._payload_descriptors

    @payload_descriptors.setter
    def payload_descriptors(self, payload_descriptors: List[ReportPayloadDescriptor]):
        """Sets the payload_descriptors of this ReportRequest.

        A list of reportPayloadDescriptors.  # noqa: E501

        :param payload_descriptors: The payload_descriptors of this ReportRequest.
        :type payload_descriptors: List[ReportPayloadDescriptor]
        """

        self._payload_descriptors = payload_descriptors

    @property
    def resources(self) -> List[ReportRequestResources]:
        """Gets the resources of this ReportRequest.

        A list of objects containing report data for a set of resources.  # noqa: E501

        :return: The resources of this ReportRequest.
        :rtype: List[ReportRequestResources]
        """
        return self._resources

    @resources.setter
    def resources(self, resources: List[ReportRequestResources]):
        """Sets the resources of this ReportRequest.

        A list of objects containing report data for a set of resources.  # noqa: E501

        :param resources: The resources of this ReportRequest.
        :type resources: List[ReportRequestResources]
        """
        if resources is None:
            raise ValueError("Invalid value for `resources`, must not be `None`")  # noqa: E501

        self._resources = resources
