# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.interval import Interval  # noqa: F401,E501
from swagger_server.models.interval_period import IntervalPeriod  # noqa: F401,E501
from swagger_server import util


class ReportResources(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, resource_id: int=None, interval_period: IntervalPeriod=None, intervals: List[Interval]=None):  # noqa: E501
        """ReportResources - a model defined in Swagger

        :param resource_id: The resource_id of this ReportResources.  # noqa: E501
        :type resource_id: int
        :param interval_period: The interval_period of this ReportResources.  # noqa: E501
        :type interval_period: IntervalPeriod
        :param intervals: The intervals of this ReportResources.  # noqa: E501
        :type intervals: List[Interval]
        """
        self.swagger_types = {
            'resource_id': int,
            'interval_period': IntervalPeriod,
            'intervals': List[Interval]
        }

        self.attribute_map = {
            'resource_id': 'resourceID',
            'interval_period': 'intervalPeriod',
            'intervals': 'intervals'
        }
        self._resource_id = resource_id
        self._interval_period = interval_period
        self._intervals = intervals

    @classmethod
    def from_dict(cls, dikt) -> 'ReportResources':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The report_resources of this ReportResources.  # noqa: E501
        :rtype: ReportResources
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resource_id(self) -> int:
        """Gets the resource_id of this ReportResources.

        User provided resource ID. A negative value indicates an aggregation of multiple resources.  # noqa: E501

        :return: The resource_id of this ReportResources.
        :rtype: int
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id: int):
        """Sets the resource_id of this ReportResources.

        User provided resource ID. A negative value indicates an aggregation of multiple resources.  # noqa: E501

        :param resource_id: The resource_id of this ReportResources.
        :type resource_id: int
        """
        if resource_id is None:
            raise ValueError("Invalid value for `resource_id`, must not be `None`")  # noqa: E501

        self._resource_id = resource_id

    @property
    def interval_period(self) -> IntervalPeriod:
        """Gets the interval_period of this ReportResources.


        :return: The interval_period of this ReportResources.
        :rtype: IntervalPeriod
        """
        return self._interval_period

    @interval_period.setter
    def interval_period(self, interval_period: IntervalPeriod):
        """Sets the interval_period of this ReportResources.


        :param interval_period: The interval_period of this ReportResources.
        :type interval_period: IntervalPeriod
        """

        self._interval_period = interval_period

    @property
    def intervals(self) -> List[Interval]:
        """Gets the intervals of this ReportResources.

        An array of interval objects.  # noqa: E501

        :return: The intervals of this ReportResources.
        :rtype: List[Interval]
        """
        return self._intervals

    @intervals.setter
    def intervals(self, intervals: List[Interval]):
        """Sets the intervals of this ReportResources.

        An array of interval objects.  # noqa: E501

        :param intervals: The intervals of this ReportResources.
        :type intervals: List[Interval]
        """

        self._intervals = intervals
