# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.report_payload_descriptor import ReportPayloadDescriptor  # noqa: F401,E501
from swagger_server.models.report_resources import ReportResources  # noqa: F401,E501
from swagger_server.models.one_ofreport_client_id import OneOfreportClientId  # noqa: F401,E501
from swagger_server import util


class Report(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: ObjectID=None, created_date_time: str=None, modification_date_time: str=None, program_id: ObjectID=None, event_id: ObjectID=None, client_id: OneOfreportClientId=None, name: str='None', payload_descriptors: List[ReportPayloadDescriptor]=None, resources: List[ReportResources]=None):  # noqa: E501
        """Report - a model defined in Swagger

        :param id: The id of this Report.  # noqa: E501
        :type id: ObjectID
        :param created_date_time: The created_date_time of this Report.  # noqa: E501
        :type created_date_time: str
        :param modification_date_time: The modification_date_time of this Report.  # noqa: E501
        :type modification_date_time: str
        :param program_id: The program_id of this Report.  # noqa: E501
        :type program_id: ObjectID
        :param event_id: The event_id of this Report.  # noqa: E501
        :type event_id: ObjectID
        :param client_id: The client_id of this Report.  # noqa: E501
        :type client_id: OneOfreportClientId
        :param name: The name of this Report.  # noqa: E501
        :type name: str
        :param payload_descriptors: The payload_descriptors of this Report.  # noqa: E501
        :type payload_descriptors: List[ReportPayloadDescriptor]
        :param resources: The resources of this Report.  # noqa: E501
        :type resources: List[ReportResources]
        """
        self.swagger_types = {
            'id': ObjectID,
            'created_date_time': str,
            'modification_date_time': str,
            'program_id': ObjectID,
            'event_id': ObjectID,
            'client_id': OneOfreportClientId,
            'name': str,
            'payload_descriptors': List[ReportPayloadDescriptor],
            'resources': List[ReportResources]
        }

        self.attribute_map = {
            'id': 'ID',
            'created_date_time': 'createdDateTime',
            'modification_date_time': 'modificationDateTime',
            'program_id': 'programID',
            'event_id': 'eventID',
            'client_id': 'clientID',
            'name': 'name',
            'payload_descriptors': 'payloadDescriptors',
            'resources': 'resources'
        }
        self._id = id
        self._created_date_time = created_date_time
        self._modification_date_time = modification_date_time
        self._program_id = program_id
        self._event_id = event_id
        self._client_id = client_id
        self._name = name
        self._payload_descriptors = payload_descriptors
        self._resources = resources

    @classmethod
    def from_dict(cls, dikt) -> 'Report':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The report of this Report.  # noqa: E501
        :rtype: Report
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> ObjectID:
        """Gets the id of this Report.


        :return: The id of this Report.
        :rtype: ObjectID
        """
        return self._id

    @id.setter
    def id(self, id: ObjectID):
        """Sets the id of this Report.


        :param id: The id of this Report.
        :type id: ObjectID
        """

        self._id = id

    @property
    def created_date_time(self) -> str:
        """Gets the created_date_time of this Report.

        Creation time for object. Server provisions timestamp string on object creation.   # noqa: E501

        :return: The created_date_time of this Report.
        :rtype: str
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time: str):
        """Sets the created_date_time of this Report.

        Creation time for object. Server provisions timestamp string on object creation.   # noqa: E501

        :param created_date_time: The created_date_time of this Report.
        :type created_date_time: str
        """

        self._created_date_time = created_date_time

    @property
    def modification_date_time(self) -> str:
        """Gets the modification_date_time of this Report.

        Modification time for object. Server provisions timestamp string on object modification.   # noqa: E501

        :return: The modification_date_time of this Report.
        :rtype: str
        """
        return self._modification_date_time

    @modification_date_time.setter
    def modification_date_time(self, modification_date_time: str):
        """Sets the modification_date_time of this Report.

        Modification time for object. Server provisions timestamp string on object modification.   # noqa: E501

        :param modification_date_time: The modification_date_time of this Report.
        :type modification_date_time: str
        """

        self._modification_date_time = modification_date_time

    @property
    def program_id(self) -> ObjectID:
        """Gets the program_id of this Report.


        :return: The program_id of this Report.
        :rtype: ObjectID
        """
        return self._program_id

    @program_id.setter
    def program_id(self, program_id: ObjectID):
        """Sets the program_id of this Report.


        :param program_id: The program_id of this Report.
        :type program_id: ObjectID
        """
        if program_id is None:
            raise ValueError("Invalid value for `program_id`, must not be `None`")  # noqa: E501

        self._program_id = program_id

    @property
    def event_id(self) -> ObjectID:
        """Gets the event_id of this Report.


        :return: The event_id of this Report.
        :rtype: ObjectID
        """
        return self._event_id

    @event_id.setter
    def event_id(self, event_id: ObjectID):
        """Sets the event_id of this Report.


        :param event_id: The event_id of this Report.
        :type event_id: ObjectID
        """
        if event_id is None:
            raise ValueError("Invalid value for `event_id`, must not be `None`")  # noqa: E501

        self._event_id = event_id

    @property
    def client_id(self) -> OneOfreportClientId:
        """Gets the client_id of this Report.

        Numeric or string ID of client, may be VEN ID provisioned during program enrollment.  # noqa: E501

        :return: The client_id of this Report.
        :rtype: OneOfreportClientId
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: OneOfreportClientId):
        """Sets the client_id of this Report.

        Numeric or string ID of client, may be VEN ID provisioned during program enrollment.  # noqa: E501

        :param client_id: The client_id of this Report.
        :type client_id: OneOfreportClientId
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def name(self) -> str:
        """Gets the name of this Report.

        User defined string for use in debugging or User Interface.  # noqa: E501

        :return: The name of this Report.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Report.

        User defined string for use in debugging or User Interface.  # noqa: E501

        :param name: The name of this Report.
        :type name: str
        """

        self._name = name

    @property
    def payload_descriptors(self) -> List[ReportPayloadDescriptor]:
        """Gets the payload_descriptors of this Report.


        :return: The payload_descriptors of this Report.
        :rtype: List[ReportPayloadDescriptor]
        """
        return self._payload_descriptors

    @payload_descriptors.setter
    def payload_descriptors(self, payload_descriptors: List[ReportPayloadDescriptor]):
        """Sets the payload_descriptors of this Report.


        :param payload_descriptors: The payload_descriptors of this Report.
        :type payload_descriptors: List[ReportPayloadDescriptor]
        """

        self._payload_descriptors = payload_descriptors

    @property
    def resources(self) -> List[ReportResources]:
        """Gets the resources of this Report.

        An array of objects containing report data for a set of resources.  # noqa: E501

        :return: The resources of this Report.
        :rtype: List[ReportResources]
        """
        return self._resources

    @resources.setter
    def resources(self, resources: List[ReportResources]):
        """Sets the resources of this Report.

        An array of objects containing report data for a set of resources.  # noqa: E501

        :param resources: The resources of this Report.
        :type resources: List[ReportResources]
        """

        self._resources = resources
