# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class ResourceRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, resource_name: str=None, ven_id: ObjectID=None, attributes: List[ValuesMap]=None, targets: List[ValuesMap]=None):  # noqa: E501
        """ResourceRequest - a model defined in Swagger

        :param resource_name: The resource_name of this ResourceRequest.  # noqa: E501
        :type resource_name: str
        :param ven_id: The ven_id of this ResourceRequest.  # noqa: E501
        :type ven_id: ObjectID
        :param attributes: The attributes of this ResourceRequest.  # noqa: E501
        :type attributes: List[ValuesMap]
        :param targets: The targets of this ResourceRequest.  # noqa: E501
        :type targets: List[ValuesMap]
        """
        self.swagger_types = {
            'resource_name': str,
            'ven_id': ObjectID,
            'attributes': List[ValuesMap],
            'targets': List[ValuesMap]
        }

        self.attribute_map = {
            'resource_name': 'resourceName',
            'ven_id': 'venID',
            'attributes': 'attributes',
            'targets': 'targets'
        }
        self._resource_name = resource_name
        self._ven_id = ven_id
        self._attributes = attributes
        self._targets = targets

    @classmethod
    def from_dict(cls, dikt) -> 'ResourceRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The resource_request of this ResourceRequest.  # noqa: E501
        :rtype: ResourceRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resource_name(self) -> str:
        """Gets the resource_name of this ResourceRequest.

        User generated identifier, resource may be configured with identifier out-of-band. resourceName is expected to be unique within the scope of the associated VEN.   # noqa: E501

        :return: The resource_name of this ResourceRequest.
        :rtype: str
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name: str):
        """Sets the resource_name of this ResourceRequest.

        User generated identifier, resource may be configured with identifier out-of-band. resourceName is expected to be unique within the scope of the associated VEN.   # noqa: E501

        :param resource_name: The resource_name of this ResourceRequest.
        :type resource_name: str
        """
        if resource_name is None:
            raise ValueError("Invalid value for `resource_name`, must not be `None`")  # noqa: E501

        self._resource_name = resource_name

    @property
    def ven_id(self) -> ObjectID:
        """Gets the ven_id of this ResourceRequest.


        :return: The ven_id of this ResourceRequest.
        :rtype: ObjectID
        """
        return self._ven_id

    @ven_id.setter
    def ven_id(self, ven_id: ObjectID):
        """Sets the ven_id of this ResourceRequest.


        :param ven_id: The ven_id of this ResourceRequest.
        :type ven_id: ObjectID
        """

        self._ven_id = ven_id

    @property
    def attributes(self) -> List[ValuesMap]:
        """Gets the attributes of this ResourceRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :return: The attributes of this ResourceRequest.
        :rtype: List[ValuesMap]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[ValuesMap]):
        """Sets the attributes of this ResourceRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :param attributes: The attributes of this ResourceRequest.
        :type attributes: List[ValuesMap]
        """

        self._attributes = attributes

    @property
    def targets(self) -> List[ValuesMap]:
        """Gets the targets of this ResourceRequest.

        A list of valuesMap objects describing target criteria.  # noqa: E501

        :return: The targets of this ResourceRequest.
        :rtype: List[ValuesMap]
        """
        return self._targets

    @targets.setter
    def targets(self, targets: List[ValuesMap]):
        """Sets the targets of this ResourceRequest.

        A list of valuesMap objects describing target criteria.  # noqa: E501

        :param targets: The targets of this ResourceRequest.
        :type targets: List[ValuesMap]
        """

        self._targets = targets
