# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server import util


class Resource(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: ObjectID=None, created_date_time: str=None, modification_date_time: str=None, resource_id: str='None', target_values: List[str]=None):  # noqa: E501
        """Resource - a model defined in Swagger

        :param id: The id of this Resource.  # noqa: E501
        :type id: ObjectID
        :param created_date_time: The created_date_time of this Resource.  # noqa: E501
        :type created_date_time: str
        :param modification_date_time: The modification_date_time of this Resource.  # noqa: E501
        :type modification_date_time: str
        :param resource_id: The resource_id of this Resource.  # noqa: E501
        :type resource_id: str
        :param target_values: The target_values of this Resource.  # noqa: E501
        :type target_values: List[str]
        """
        self.swagger_types = {
            'id': ObjectID,
            'created_date_time': str,
            'modification_date_time': str,
            'resource_id': str,
            'target_values': List[str]
        }

        self.attribute_map = {
            'id': 'ID',
            'created_date_time': 'createdDateTime',
            'modification_date_time': 'modificationDateTime',
            'resource_id': 'resourceID',
            'target_values': 'targetValues'
        }
        self._id = id
        self._created_date_time = created_date_time
        self._modification_date_time = modification_date_time
        self._resource_id = resource_id
        self._target_values = target_values

    @classmethod
    def from_dict(cls, dikt) -> 'Resource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The resource of this Resource.  # noqa: E501
        :rtype: Resource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> ObjectID:
        """Gets the id of this Resource.


        :return: The id of this Resource.
        :rtype: ObjectID
        """
        return self._id

    @id.setter
    def id(self, id: ObjectID):
        """Sets the id of this Resource.


        :param id: The id of this Resource.
        :type id: ObjectID
        """

        self._id = id

    @property
    def created_date_time(self) -> str:
        """Gets the created_date_time of this Resource.

        Creation time for object. Server provisions timestamp string on object creation.   # noqa: E501

        :return: The created_date_time of this Resource.
        :rtype: str
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time: str):
        """Sets the created_date_time of this Resource.

        Creation time for object. Server provisions timestamp string on object creation.   # noqa: E501

        :param created_date_time: The created_date_time of this Resource.
        :type created_date_time: str
        """

        self._created_date_time = created_date_time

    @property
    def modification_date_time(self) -> str:
        """Gets the modification_date_time of this Resource.

        Modification time for object. Server provisions timestamp string on object modification.   # noqa: E501

        :return: The modification_date_time of this Resource.
        :rtype: str
        """
        return self._modification_date_time

    @modification_date_time.setter
    def modification_date_time(self, modification_date_time: str):
        """Sets the modification_date_time of this Resource.

        Modification time for object. Server provisions timestamp string on object modification.   # noqa: E501

        :param modification_date_time: The modification_date_time of this Resource.
        :type modification_date_time: str
        """

        self._modification_date_time = modification_date_time

    @property
    def resource_id(self) -> str:
        """Gets the resource_id of this Resource.

        String identifier for resource. resource may be configured with ID out-of-band.  # noqa: E501

        :return: The resource_id of this Resource.
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id: str):
        """Sets the resource_id of this Resource.

        String identifier for resource. resource may be configured with ID out-of-band.  # noqa: E501

        :param resource_id: The resource_id of this Resource.
        :type resource_id: str
        """

        self._resource_id = resource_id

    @property
    def target_values(self) -> List[str]:
        """Gets the target_values of this Resource.


        :return: The target_values of this Resource.
        :rtype: List[str]
        """
        return self._target_values

    @target_values.setter
    def target_values(self, target_values: List[str]):
        """Sets the target_values of this Resource.


        :param target_values: The target_values of this Resource.
        :type target_values: List[str]
        """

        self._target_values = target_values
