# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.subscription_resource_operations import SubscriptionResourceOperations  # noqa: F401,E501
from swagger_server import util


class Subscription(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: ObjectID=None, created_date_time: str=None, modification_date_time: str=None, client_id: ObjectID=None, program_id: ObjectID=None, resource_operations: List[SubscriptionResourceOperations]=None):  # noqa: E501
        """Subscription - a model defined in Swagger

        :param id: The id of this Subscription.  # noqa: E501
        :type id: ObjectID
        :param created_date_time: The created_date_time of this Subscription.  # noqa: E501
        :type created_date_time: str
        :param modification_date_time: The modification_date_time of this Subscription.  # noqa: E501
        :type modification_date_time: str
        :param client_id: The client_id of this Subscription.  # noqa: E501
        :type client_id: ObjectID
        :param program_id: The program_id of this Subscription.  # noqa: E501
        :type program_id: ObjectID
        :param resource_operations: The resource_operations of this Subscription.  # noqa: E501
        :type resource_operations: List[SubscriptionResourceOperations]
        """
        self.swagger_types = {
            'id': ObjectID,
            'created_date_time': str,
            'modification_date_time': str,
            'client_id': ObjectID,
            'program_id': ObjectID,
            'resource_operations': List[SubscriptionResourceOperations]
        }

        self.attribute_map = {
            'id': 'ID',
            'created_date_time': 'createdDateTime',
            'modification_date_time': 'modificationDateTime',
            'client_id': 'clientID',
            'program_id': 'programID',
            'resource_operations': 'resourceOperations'
        }
        self._id = id
        self._created_date_time = created_date_time
        self._modification_date_time = modification_date_time
        self._client_id = client_id
        self._program_id = program_id
        self._resource_operations = resource_operations

    @classmethod
    def from_dict(cls, dikt) -> 'Subscription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The subscription of this Subscription.  # noqa: E501
        :rtype: Subscription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> ObjectID:
        """Gets the id of this Subscription.


        :return: The id of this Subscription.
        :rtype: ObjectID
        """
        return self._id

    @id.setter
    def id(self, id: ObjectID):
        """Sets the id of this Subscription.


        :param id: The id of this Subscription.
        :type id: ObjectID
        """

        self._id = id

    @property
    def created_date_time(self) -> str:
        """Gets the created_date_time of this Subscription.

        Creation time for object. Server provisions timestamp string on object creation.   # noqa: E501

        :return: The created_date_time of this Subscription.
        :rtype: str
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time: str):
        """Sets the created_date_time of this Subscription.

        Creation time for object. Server provisions timestamp string on object creation.   # noqa: E501

        :param created_date_time: The created_date_time of this Subscription.
        :type created_date_time: str
        """

        self._created_date_time = created_date_time

    @property
    def modification_date_time(self) -> str:
        """Gets the modification_date_time of this Subscription.

        Modification time for object. Server provisions timestamp string on object modification.   # noqa: E501

        :return: The modification_date_time of this Subscription.
        :rtype: str
        """
        return self._modification_date_time

    @modification_date_time.setter
    def modification_date_time(self, modification_date_time: str):
        """Sets the modification_date_time of this Subscription.

        Modification time for object. Server provisions timestamp string on object modification.   # noqa: E501

        :param modification_date_time: The modification_date_time of this Subscription.
        :type modification_date_time: str
        """

        self._modification_date_time = modification_date_time

    @property
    def client_id(self) -> ObjectID:
        """Gets the client_id of this Subscription.


        :return: The client_id of this Subscription.
        :rtype: ObjectID
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: ObjectID):
        """Sets the client_id of this Subscription.


        :param client_id: The client_id of this Subscription.
        :type client_id: ObjectID
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def program_id(self) -> ObjectID:
        """Gets the program_id of this Subscription.


        :return: The program_id of this Subscription.
        :rtype: ObjectID
        """
        return self._program_id

    @program_id.setter
    def program_id(self, program_id: ObjectID):
        """Sets the program_id of this Subscription.


        :param program_id: The program_id of this Subscription.
        :type program_id: ObjectID
        """
        if program_id is None:
            raise ValueError("Invalid value for `program_id`, must not be `None`")  # noqa: E501

        self._program_id = program_id

    @property
    def resource_operations(self) -> List[SubscriptionResourceOperations]:
        """Gets the resource_operations of this Subscription.

        list of resources and operations to subscribe to.  # noqa: E501

        :return: The resource_operations of this Subscription.
        :rtype: List[SubscriptionResourceOperations]
        """
        return self._resource_operations

    @resource_operations.setter
    def resource_operations(self, resource_operations: List[SubscriptionResourceOperations]):
        """Sets the resource_operations of this Subscription.

        list of resources and operations to subscribe to.  # noqa: E501

        :param resource_operations: The resource_operations of this Subscription.
        :type resource_operations: List[SubscriptionResourceOperations]
        """
        if resource_operations is None:
            raise ValueError("Invalid value for `resource_operations`, must not be `None`")  # noqa: E501

        self._resource_operations = resource_operations
