# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.client_name import ClientName  # noqa: F401,E501
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.subscription_request_object_operations import SubscriptionRequestObjectOperations  # noqa: F401,E501
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class SubscriptionRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, client_name: ClientName=None, program_id: ObjectID=None, object_operations: List[SubscriptionRequestObjectOperations]=None, targets: List[ValuesMap]=None):  # noqa: E501
        """SubscriptionRequest - a model defined in Swagger

        :param client_name: The client_name of this SubscriptionRequest.  # noqa: E501
        :type client_name: ClientName
        :param program_id: The program_id of this SubscriptionRequest.  # noqa: E501
        :type program_id: ObjectID
        :param object_operations: The object_operations of this SubscriptionRequest.  # noqa: E501
        :type object_operations: List[SubscriptionRequestObjectOperations]
        :param targets: The targets of this SubscriptionRequest.  # noqa: E501
        :type targets: List[ValuesMap]
        """
        self.swagger_types = {
            'client_name': ClientName,
            'program_id': ObjectID,
            'object_operations': List[SubscriptionRequestObjectOperations],
            'targets': List[ValuesMap]
        }

        self.attribute_map = {
            'client_name': 'clientName',
            'program_id': 'programID',
            'object_operations': 'objectOperations',
            'targets': 'targets'
        }
        self._client_name = client_name
        self._program_id = program_id
        self._object_operations = object_operations
        self._targets = targets

    @classmethod
    def from_dict(cls, dikt) -> 'SubscriptionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The subscriptionRequest of this SubscriptionRequest.  # noqa: E501
        :rtype: SubscriptionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client_name(self) -> ClientName:
        """Gets the client_name of this SubscriptionRequest.


        :return: The client_name of this SubscriptionRequest.
        :rtype: ClientName
        """
        return self._client_name

    @client_name.setter
    def client_name(self, client_name: ClientName):
        """Sets the client_name of this SubscriptionRequest.


        :param client_name: The client_name of this SubscriptionRequest.
        :type client_name: ClientName
        """
        if client_name is None:
            raise ValueError("Invalid value for `client_name`, must not be `None`")  # noqa: E501

        self._client_name = client_name

    @property
    def program_id(self) -> ObjectID:
        """Gets the program_id of this SubscriptionRequest.


        :return: The program_id of this SubscriptionRequest.
        :rtype: ObjectID
        """
        return self._program_id

    @program_id.setter
    def program_id(self, program_id: ObjectID):
        """Sets the program_id of this SubscriptionRequest.


        :param program_id: The program_id of this SubscriptionRequest.
        :type program_id: ObjectID
        """

        self._program_id = program_id

    @property
    def object_operations(self) -> List[SubscriptionRequestObjectOperations]:
        """Gets the object_operations of this SubscriptionRequest.

        list of objects and operations to subscribe to.  # noqa: E501

        :return: The object_operations of this SubscriptionRequest.
        :rtype: List[SubscriptionRequestObjectOperations]
        """
        return self._object_operations

    @object_operations.setter
    def object_operations(self, object_operations: List[SubscriptionRequestObjectOperations]):
        """Sets the object_operations of this SubscriptionRequest.

        list of objects and operations to subscribe to.  # noqa: E501

        :param object_operations: The object_operations of this SubscriptionRequest.
        :type object_operations: List[SubscriptionRequestObjectOperations]
        """
        if object_operations is None:
            raise ValueError("Invalid value for `object_operations`, must not be `None`")  # noqa: E501

        self._object_operations = object_operations

    @property
    def targets(self) -> List[ValuesMap]:
        """Gets the targets of this SubscriptionRequest.

        A list of valuesMap objects. Used by server to filter callbacks.  # noqa: E501

        :return: The targets of this SubscriptionRequest.
        :rtype: List[ValuesMap]
        """
        return self._targets

    @targets.setter
    def targets(self, targets: List[ValuesMap]):
        """Sets the targets of this SubscriptionRequest.

        A list of valuesMap objects. Used by server to filter callbacks.  # noqa: E501

        :param targets: The targets of this SubscriptionRequest.
        :type targets: List[ValuesMap]
        """

        self._targets = targets
