# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Target(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, target_type: str=None, values: List[str]=None):  # noqa: E501
        """Target - a model defined in Swagger

        :param target_type: The target_type of this Target.  # noqa: E501
        :type target_type: str
        :param values: The values of this Target.  # noqa: E501
        :type values: List[str]
        """
        self.swagger_types = {
            'target_type': str,
            'values': List[str]
        }

        self.attribute_map = {
            'target_type': 'targetType',
            'values': 'values'
        }
        self._target_type = target_type
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'Target':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The target of this Target.  # noqa: E501
        :rtype: Target
        """
        return util.deserialize_model(dikt, cls)

    @property
    def target_type(self) -> str:
        """Gets the target_type of this Target.

        Enumerated or private string signifying the type of target.  # noqa: E501

        :return: The target_type of this Target.
        :rtype: str
        """
        return self._target_type

    @target_type.setter
    def target_type(self, target_type: str):
        """Sets the target_type of this Target.

        Enumerated or private string signifying the type of target.  # noqa: E501

        :param target_type: The target_type of this Target.
        :type target_type: str
        """
        if target_type is None:
            raise ValueError("Invalid value for `target_type`, must not be `None`")  # noqa: E501

        self._target_type = target_type

    @property
    def values(self) -> List[str]:
        """Gets the values of this Target.

        A list of values.  # noqa: E501

        :return: The values of this Target.
        :rtype: List[str]
        """
        return self._values

    @values.setter
    def values(self, values: List[str]):
        """Sets the values of this Target.

        A list of values.  # noqa: E501

        :param values: The values of this Target.
        :type values: List[str]
        """
        if values is None:
            raise ValueError("Invalid value for `values`, must not be `None`")  # noqa: E501

        self._values = values
