# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object_id import ObjectID  # noqa: F401,E501
from swagger_server.models.resource import Resource  # noqa: F401,E501
from swagger_server import util


class Ven(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: ObjectID=None, created_date_time: str=None, modification_date_time: str=None, ven_id: str=None, target_values: List[str]=None, resources: List[Resource]=None):  # noqa: E501
        """Ven - a model defined in Swagger

        :param id: The id of this Ven.  # noqa: E501
        :type id: ObjectID
        :param created_date_time: The created_date_time of this Ven.  # noqa: E501
        :type created_date_time: str
        :param modification_date_time: The modification_date_time of this Ven.  # noqa: E501
        :type modification_date_time: str
        :param ven_id: The ven_id of this Ven.  # noqa: E501
        :type ven_id: str
        :param target_values: The target_values of this Ven.  # noqa: E501
        :type target_values: List[str]
        :param resources: The resources of this Ven.  # noqa: E501
        :type resources: List[Resource]
        """
        self.swagger_types = {
            'id': ObjectID,
            'created_date_time': str,
            'modification_date_time': str,
            'ven_id': str,
            'target_values': List[str],
            'resources': List[Resource]
        }

        self.attribute_map = {
            'id': 'ID',
            'created_date_time': 'createdDateTime',
            'modification_date_time': 'modificationDateTime',
            'ven_id': 'venID',
            'target_values': 'targetValues',
            'resources': 'resources'
        }
        self._id = id
        self._created_date_time = created_date_time
        self._modification_date_time = modification_date_time
        self._ven_id = ven_id
        self._target_values = target_values
        self._resources = resources

    @classmethod
    def from_dict(cls, dikt) -> 'Ven':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ven of this Ven.  # noqa: E501
        :rtype: Ven
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> ObjectID:
        """Gets the id of this Ven.


        :return: The id of this Ven.
        :rtype: ObjectID
        """
        return self._id

    @id.setter
    def id(self, id: ObjectID):
        """Sets the id of this Ven.


        :param id: The id of this Ven.
        :type id: ObjectID
        """

        self._id = id

    @property
    def created_date_time(self) -> str:
        """Gets the created_date_time of this Ven.

        Creation time for object. Server provisions timestamp string on object creation.   # noqa: E501

        :return: The created_date_time of this Ven.
        :rtype: str
        """
        return self._created_date_time

    @created_date_time.setter
    def created_date_time(self, created_date_time: str):
        """Sets the created_date_time of this Ven.

        Creation time for object. Server provisions timestamp string on object creation.   # noqa: E501

        :param created_date_time: The created_date_time of this Ven.
        :type created_date_time: str
        """

        self._created_date_time = created_date_time

    @property
    def modification_date_time(self) -> str:
        """Gets the modification_date_time of this Ven.

        Modification time for object. Server provisions timestamp string on object modification.   # noqa: E501

        :return: The modification_date_time of this Ven.
        :rtype: str
        """
        return self._modification_date_time

    @modification_date_time.setter
    def modification_date_time(self, modification_date_time: str):
        """Sets the modification_date_time of this Ven.

        Modification time for object. Server provisions timestamp string on object modification.   # noqa: E501

        :param modification_date_time: The modification_date_time of this Ven.
        :type modification_date_time: str
        """

        self._modification_date_time = modification_date_time

    @property
    def ven_id(self) -> str:
        """Gets the ven_id of this Ven.

        String identifier for VEN. VEN may be configured with ID out-of-band.  # noqa: E501

        :return: The ven_id of this Ven.
        :rtype: str
        """
        return self._ven_id

    @ven_id.setter
    def ven_id(self, ven_id: str):
        """Sets the ven_id of this Ven.

        String identifier for VEN. VEN may be configured with ID out-of-band.  # noqa: E501

        :param ven_id: The ven_id of this Ven.
        :type ven_id: str
        """

        self._ven_id = ven_id

    @property
    def target_values(self) -> List[str]:
        """Gets the target_values of this Ven.


        :return: The target_values of this Ven.
        :rtype: List[str]
        """
        return self._target_values

    @target_values.setter
    def target_values(self, target_values: List[str]):
        """Sets the target_values of this Ven.


        :param target_values: The target_values of this Ven.
        :type target_values: List[str]
        """

        self._target_values = target_values

    @property
    def resources(self) -> List[Resource]:
        """Gets the resources of this Ven.

        An array of resource objects representing end-devices or systems.  # noqa: E501

        :return: The resources of this Ven.
        :rtype: List[Resource]
        """
        return self._resources

    @resources.setter
    def resources(self, resources: List[Resource]):
        """Sets the resources of this Ven.

        An array of resource objects representing end-devices or systems.  # noqa: E501

        :param resources: The resources of this Ven.
        :type resources: List[Resource]
        """

        self._resources = resources
