# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.resource import Resource  # noqa: F401,E501
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
from swagger_server import util


class VenRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ven_name: str=None, attributes: List[ValuesMap]=None, targets: List[ValuesMap]=None, resources: List[Resource]=None):  # noqa: E501
        """VenRequest - a model defined in Swagger

        :param ven_name: The ven_name of this VenRequest.  # noqa: E501
        :type ven_name: str
        :param attributes: The attributes of this VenRequest.  # noqa: E501
        :type attributes: List[ValuesMap]
        :param targets: The targets of this VenRequest.  # noqa: E501
        :type targets: List[ValuesMap]
        :param resources: The resources of this VenRequest.  # noqa: E501
        :type resources: List[Resource]
        """
        self.swagger_types = {
            'ven_name': str,
            'attributes': List[ValuesMap],
            'targets': List[ValuesMap],
            'resources': List[Resource]
        }

        self.attribute_map = {
            'ven_name': 'venName',
            'attributes': 'attributes',
            'targets': 'targets',
            'resources': 'resources'
        }
        self._ven_name = ven_name
        self._attributes = attributes
        self._targets = targets
        self._resources = resources

    @classmethod
    def from_dict(cls, dikt) -> 'VenRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The venRequest of this VenRequest.  # noqa: E501
        :rtype: VenRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ven_name(self) -> str:
        """Gets the ven_name of this VenRequest.

        User generated identifier, may be VEN identifier provisioned out-of-band. venName is expected to be unique within the scope of a VTN   # noqa: E501

        :return: The ven_name of this VenRequest.
        :rtype: str
        """
        return self._ven_name

    @ven_name.setter
    def ven_name(self, ven_name: str):
        """Sets the ven_name of this VenRequest.

        User generated identifier, may be VEN identifier provisioned out-of-band. venName is expected to be unique within the scope of a VTN   # noqa: E501

        :param ven_name: The ven_name of this VenRequest.
        :type ven_name: str
        """
        if ven_name is None:
            raise ValueError("Invalid value for `ven_name`, must not be `None`")  # noqa: E501

        self._ven_name = ven_name

    @property
    def attributes(self) -> List[ValuesMap]:
        """Gets the attributes of this VenRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :return: The attributes of this VenRequest.
        :rtype: List[ValuesMap]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[ValuesMap]):
        """Sets the attributes of this VenRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :param attributes: The attributes of this VenRequest.
        :type attributes: List[ValuesMap]
        """

        self._attributes = attributes

    @property
    def targets(self) -> List[ValuesMap]:
        """Gets the targets of this VenRequest.

        A list of valuesMap objects describing target criteria.  # noqa: E501

        :return: The targets of this VenRequest.
        :rtype: List[ValuesMap]
        """
        return self._targets

    @targets.setter
    def targets(self, targets: List[ValuesMap]):
        """Sets the targets of this VenRequest.

        A list of valuesMap objects describing target criteria.  # noqa: E501

        :param targets: The targets of this VenRequest.
        :type targets: List[ValuesMap]
        """

        self._targets = targets

    @property
    def resources(self) -> List[Resource]:
        """Gets the resources of this VenRequest.

        A list of resource objects representing end-devices or systems.  # noqa: E501

        :return: The resources of this VenRequest.
        :rtype: List[Resource]
        """
        return self._resources

    @resources.setter
    def resources(self, resources: List[Resource]):
        """Sets the resources of this VenRequest.

        A list of resource objects representing end-devices or systems.  # noqa: E501

        :param resources: The resources of this VenRequest.
        :type resources: List[Resource]
        """

        self._resources = resources
