# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.values_map import ValuesMap  # noqa: F401,E501
from swagger_server.models.ven_name import VenName  # noqa: F401,E501
from swagger_server import util


class VenVenRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, object_type: str=None, ven_name: VenName=None, attributes: List[ValuesMap]=None):  # noqa: E501
        """VenVenRequest - a model defined in Swagger

        :param object_type: The object_type of this VenVenRequest.  # noqa: E501
        :type object_type: str
        :param ven_name: The ven_name of this VenVenRequest.  # noqa: E501
        :type ven_name: VenName
        :param attributes: The attributes of this VenVenRequest.  # noqa: E501
        :type attributes: List[ValuesMap]
        """
        self.swagger_types = {
            'object_type': str,
            'ven_name': VenName,
            'attributes': List[ValuesMap]
        }

        self.attribute_map = {
            'object_type': 'objectType',
            'ven_name': 'venName',
            'attributes': 'attributes'
        }
        self._object_type = object_type
        self._ven_name = ven_name
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'VenVenRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VenVenRequest of this VenVenRequest.  # noqa: E501
        :rtype: VenVenRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def object_type(self) -> str:
        """Gets the object_type of this VenVenRequest.

        Used as discriminator.  # noqa: E501

        :return: The object_type of this VenVenRequest.
        :rtype: str
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type: str):
        """Sets the object_type of this VenVenRequest.

        Used as discriminator.  # noqa: E501

        :param object_type: The object_type of this VenVenRequest.
        :type object_type: str
        """
        allowed_values = ["VEN_VEN_REQUEST"]  # noqa: E501
        if object_type not in allowed_values:
            raise ValueError(
                "Invalid value for `object_type` ({0}), must be one of {1}"
                .format(object_type, allowed_values)
            )

        self._object_type = object_type

    @property
    def ven_name(self) -> VenName:
        """Gets the ven_name of this VenVenRequest.


        :return: The ven_name of this VenVenRequest.
        :rtype: VenName
        """
        return self._ven_name

    @ven_name.setter
    def ven_name(self, ven_name: VenName):
        """Sets the ven_name of this VenVenRequest.


        :param ven_name: The ven_name of this VenVenRequest.
        :type ven_name: VenName
        """
        if ven_name is None:
            raise ValueError("Invalid value for `ven_name`, must not be `None`")  # noqa: E501

        self._ven_name = ven_name

    @property
    def attributes(self) -> List[ValuesMap]:
        """Gets the attributes of this VenVenRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :return: The attributes of this VenVenRequest.
        :rtype: List[ValuesMap]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[ValuesMap]):
        """Sets the attributes of this VenVenRequest.

        A list of valuesMap objects describing attributes.  # noqa: E501

        :param attributes: The attributes of this VenVenRequest.
        :type attributes: List[ValuesMap]
        """

        self._attributes = attributes
