import connexion
import six

from swagger_server.models.notifier_topics_response import NotifierTopicsResponse  # noqa: E501
from swagger_server.models.object_id import ObjectID  # noqa: E501
from swagger_server.models.problem import Problem  # noqa: E501
from swagger_server import util

# Added to autogenerated stub
from swagger_server.models.notifier_topics_response import NotifierTopicsResponse
from swagger_server.models.notifier_operations_topics import NotifierOperationsTopics  # noqa: F401,E501
from swagger_server.models.program import Program  # noqa: E501
from swagger_server.models.ven import Ven  # noqa: E501
from swagger_server.objStore.storageInterface import objStore
from swagger_server.mqtt import path
from config import \
    NOTIFIER_BINDINGS, \
    MQTT_TOPIC_BASE_PROGRAMS, \
    MQTT_TOPIC_BASE_PROGRAM_EVENTS, \
    MQTT_TOPIC_BASE_EVENTS, \
    MQTT_TOPIC_BASE_REPORTS, \
    MQTT_TOPIC_BASE_SUBSCRIPTIONS, \
    MQTT_TOPIC_BASE_RESOURCES, \
    MQTT_TOPIC_BASE_VENS, \
    MQTT_TOPIC_BASE_VEN_RESOURCES, \
    MQTT_TOPIC_BASE_VEN_PROGRAMS, \
    MQTT_TOPIC_BASE_VEN_EVENTS

from http import HTTPStatus
import logging


def invalid_program_id(program_id: str) -> bool:
    program = objStore.search("PROGRAM", program_id)
    return type(program) is not Program


def invalid_ven_id(ven_id: str) -> bool:
    ven = objStore.search("VEN", ven_id)
    return type(ven) is not Ven


def topics(basepath: str, id: str = None) -> NotifierTopicsResponse:
    return NotifierTopicsResponse(
        topics=NotifierOperationsTopics(
            create=path(basepath, 'create', id),
            update=path(basepath, 'update', id),
            delete=path(basepath, 'delete', id),
            all=path(basepath, '+', id)))


def topics_no_create(basepath: str, id: str = None) -> NotifierTopicsResponse:
    return NotifierTopicsResponse(
        topics=NotifierOperationsTopics(
            update=path(basepath, 'update', id),
            delete=path(basepath, 'delete', id),
            all=path(basepath, '+', id)))


def list_all_mqtt_notifier_topics_events():  # noqa: E501
    """List all MQTT binding topic names for operations on all events

    List all MQTT binding topic names for operations on all events  # noqa: E501


    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_events(): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_notifier_topics_events()")

    response = topics(MQTT_TOPIC_BASE_EVENTS)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_program(program_id):  # noqa: E501
    """List all MQTT binding topic names for operations on a program

    List all MQTT binding topic names for operations on a program  # noqa: E501

    :param program_id: objectID of the program object
    :type program_id: dict | bytes

    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_program({program_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND
    elif invalid_program_id(program_id):
        problem = Problem(title=f"programID={program_id} not found", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_program(): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_notifier_topics_program({program_id})")

    response = topics_no_create(MQTT_TOPIC_BASE_PROGRAMS, program_id)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_program_events(program_id):  # noqa: E501
    """List all MQTT binding topic names for operations on events for a program

    List all MQTT binding topic names for operations on events for a program  # noqa: E501

    :param program_id: Object ID of the program object
    :type program_id: dict | bytes

    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_program_events({program_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND
    elif invalid_program_id(program_id):
        problem = Problem(title=f"programID={program_id} not found", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_program_events({program_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_notifier_topics_program_events({program_id})")

    response = topics(MQTT_TOPIC_BASE_PROGRAM_EVENTS, program_id)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_programs():  # noqa: E501
    """List all MQTT notifier topic names for operations on programs

    List all MQTT notifier topic names for operations on programs  # noqa: E501


    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_programs(): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_topics_notifier_programs()")

    response = topics(MQTT_TOPIC_BASE_PROGRAMS)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_reports():  # noqa: E501
    """List all MQTT binding topic names for operations on all reports

    List all MQTT binding topic names for operations on all reports  # noqa: E501


    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_reports(): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_topics_notifier_reports()")

    response = topics(MQTT_TOPIC_BASE_REPORTS)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_resources():  # noqa: E501
    """List all MQTT binding topic names for operations on resources

    List all MQTT binding topic names for operations on resources  # noqa: E501


    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_resources(): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_topics_notifier_resources()")

    response = topics(MQTT_TOPIC_BASE_RESOURCES)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_subscriptions():  # noqa: E501
    """List all MQTT binding topic names for operations on all subscriptions

    List all MQTT binding topic names for operations on all subscriptions  # noqa: E501


    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_subscriptions(): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_topics_notifier_subscriptions()")

    response = topics(MQTT_TOPIC_BASE_SUBSCRIPTIONS)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_ven(ven_id):  # noqa: E501
    """List all MQTT binding topic names for operations on a ven

    List all MQTT binding topic names for operations on a ven  # noqa: E501

    :param ven_id: venID of the vens object
    :type ven_id: dict | bytes

    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_ven({ven_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND
    elif invalid_ven_id(ven_id):
        problem = Problem(title=f"venID={ven_id} not found", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_ven({ven_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_notifier_topics_ven({ven_id})")

    response = topics_no_create(MQTT_TOPIC_BASE_VENS, ven_id)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_ven_events(ven_id):  # noqa: E501
    """List all MQTT binding topic names for operations on events targeted for a ven

    List all MQTT binding topic names for operations on events targated for a ven  # noqa: E501

    :param ven_id: object ID of the ven object
    :type ven_id: dict | bytes

    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_ven_events({ven_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND
    elif invalid_ven_id(ven_id):
        problem = Problem(title=f"venID={ven_id} not found", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_ven_events({ven_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_notifier_topics_ven_events({ven_id})")

    response = topics(MQTT_TOPIC_BASE_VEN_EVENTS, ven_id)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_ven_programs(ven_id):  # noqa: E501
    """List all MQTT binding topic names for operations on programs targeted for a ven

    List all MQTT binding topic names for operations on programs targeted for a ven  # noqa: E501

    :param ven_id: object ID of the ven object
    :type ven_id: dict | bytes

    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_ven_programs({ven_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND
    elif invalid_ven_id(ven_id):
        problem = Problem(title=f"venID={ven_id} not found", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_ven_programs({ven_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_notifier_topics_ven_programs({ven_id})")

    response = topics(MQTT_TOPIC_BASE_VEN_PROGRAMS, ven_id)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_ven_resources(ven_id):  # noqa: E501
    """List all MQTT binding topic names for operations on resources for a ven

    List all MQTT binding topic names for operations on resources for a ven  # noqa: E501

    :param ven_id: object ID of the ven object
    :type ven_id: dict | bytes

    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_ven_resources({ven_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND
    elif invalid_ven_id(ven_id):
        problem = Problem(title=f"venID={ven_id} not found", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_ven_resources({ven_id}): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_notifier_topics_ven_resources({ven_id})")

    response = topics(MQTT_TOPIC_BASE_VEN_RESOURCES, ven_id)
    return response, HTTPStatus.OK


def list_all_mqtt_notifier_topics_vens():  # noqa: E501
    """List all MQTT binding topic names for operations on vens

    List all MQTT binding topic names for operations on vens  # noqa: E501


    :rtype: NotifierTopicsResponse
    """
    if not 'MQTT' in NOTIFIER_BINDINGS:
        problem = Problem(title="MQTT binding not enabled", status=HTTPStatus.NOT_FOUND)
        logging.warning(f"list_all_mqtt_notifier_topics_vens(): problem={problem}")
        return problem, HTTPStatus.NOT_FOUND

    logging.info(f"list_all_mqtt_notifier_topics_vens()")

    response = topics(MQTT_TOPIC_BASE_VENS)
    return response, HTTPStatus.OK
