import connexion
import six

from swagger_server.models.notifiers_response import NotifiersResponse  # noqa: E501
from swagger_server.models.problem import Problem  # noqa: E501
from swagger_server import util

# Added to autogenerated stub
import logging
from flask import request
from swagger_server import mqtt
from swagger_server import globals
from swagger_server import objectUtils
from config import NOTIFIER_BINDINGS, MQTT_BROKER_AUTH
from http import HTTPStatus


def _lookup_mqtt_credentials(request):
    """Look up MQTT credentials for the caller, if dynsec is active."""
    if not globals.DYNSEC or MQTT_BROKER_AUTH == 'ANONYMOUS':
        return None, None
    client_id = objectUtils.getClientId(request)
    if not client_id:
        return None, None
    role = objectUtils.getClientRole(request)
    if role == 'BL':
        creds = globals.BL_MQTT_CREDENTIALS.get(client_id)
        if creds:
            return creds.get('username'), creds.get('password')
    else:
        # VEN — find ven_id by client_id, first check in-memory VENS dict,
        # then fall back to object store (needed after VTN restart when VENS
        # dict hasn't been populated yet by ven_tracker)
        ven_id = None
        for vid, ven_record in globals.VENS.items():
            if ven_record.get('client_id') == client_id:
                ven_id = vid
                break
        if ven_id is None:
            # Fall back to object store
            from swagger_server.objStore.storageInterface import objStore
            vens = objStore.search_all("VEN")
            if isinstance(vens, list):
                for ven in vens:
                    if getattr(ven, 'client_id', None) == client_id:
                        ven_id = getattr(ven, 'id', None)
                        break
        if ven_id:
            creds = globals.VEN_MQTT_CREDENTIALS.get(ven_id)
            if creds:
                return creds.get('username'), creds.get('password')
    return None, None


def list_all_notifiers():  # noqa: E501
    """List all notifier bindings

    List all notifier bindings supported by the server  # noqa: E501


    :rtype: NotifiersResponse
    """
    logging.info(f"list_all_notifiers()")

    if 'MQTT' in NOTIFIER_BINDINGS:
        mqtt_username, mqtt_password = _lookup_mqtt_credentials(request)
        mqtt_binding = mqtt.binding(mqtt_username=mqtt_username, mqtt_password=mqtt_password)
        if mqtt_binding:
            notifiers_response = NotifiersResponse(webhook=True,
                                                   mqtt=mqtt_binding)
        else:
            notifiers_response = NotifiersResponse(webhook=True)
    else:
        # TODO: If/when additional notifier bindings defined/supported, add their binding() call here
        notifiers_response = NotifiersResponse(webhook=True)

    return notifiers_response, HTTPStatus.OK
