import connexion
import six

from swagger_server.models.notifiers_response import NotifiersResponse  # noqa: E501
from swagger_server.models.problem import Problem  # noqa: E501
from swagger_server import util

# Added to autogenerated stub
import logging
from swagger_server import mqtt
from config import NOTIFIER_BINDINGS
from http import HTTPStatus

def list_all_notifiers():  # noqa: E501
    """List all notifier bindings

    List all notifier bindings supported by the server  # noqa: E501


    :rtype: NotifiersResponse
    """
    logging.info(f"list_all_notifiers()")

    if 'MQTT' in NOTIFIER_BINDINGS:
        mqtt_binding = mqtt.binding()
        if mqtt_binding:
            notifiers_response = NotifiersResponse(webhook=True,
                                                   mqtt=mqtt_binding)
        else:
            notifiers__response = NotifiersResponse(webhook=True)
    else:
        # TODO: If/when additional notifier bindings defined/supported, add their binding() call here
        notifiers_response = NotifiersResponse(webhook=True)

    return notifiers_response, HTTPStatus.OK
