name: Build image in ECR

on:
  push:
    # branches:
    #   - "main"
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      - name: Set ECR_REGISTRY
        run: export ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
      - name: Set ECR_REPOSITORY
        run: export ECR_REPOSITORY=oadr-ri
      - name: Set IMAGE_NAME
        run: export IMAGE_NAME=oadr-ri
      - name: Get version
        run: echo "$(git rev-parse --short HEAD)"
      - name: Set IMAGE_VERSION
        run: export IMAGE_VERSION=$(git rev-parse --short HEAD)
      - name: Build docker image
        run: docker build . -t oadr-ri:$(git rev-parse --short HEAD)
      - name: Push image
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION
